// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {options} from '../models';

export function AddLocalPlaylistItem(arg1:string,arg2:desktop.LocalPlaylistItem):Promise<void>;

export function ChooseLocalFolder():Promise<string>;

export function ClearAllRecent():Promise<void>;

export function ClearArtworkCache():Promise<void>;

export function ClearLocalFolder(arg1:string):Promise<void>;

export function ConnectToServer(arg1:string,arg2:string,arg3:string):Promise<desktop.ConnectResult>;

export function CreateLocalPlaylist(arg1:string,arg2:string):Promise<desktop.LocalPlaylistSummary>;

export function DeleteLocalPlaylist(arg1:string):Promise<void>;

export function DisconnectFromServer():Promise<void>;

export function GetLocalAlbumGroups(arg1:Array<string>,arg2:string,arg3:number,arg4:number):Promise<desktop.LocalAlbumGroupsResult>;

export function GetLocalAlbumTracks(arg1:Array<string>,arg2:string,arg3:string):Promise<Array<desktop.LocalTrack>>;

export function GetLocalPlaylistItems(arg1:string):Promise<Array<desktop.LocalPlaylistItem>>;

export function GetLocalPlaylists():Promise<Array<desktop.LocalPlaylistSummary>>;

export function GetLocalPort():Promise<number>;

export function GetLocalTracks(arg1:Array<string>):Promise<Array<desktop.LocalTrack>>;

export function GetLocalTracksByPaths(arg1:Array<string>):Promise<Array<desktop.LocalTrack>>;

export function GetLocalTracksPage(arg1:Array<string>,arg2:number,arg3:number):Promise<Array<desktop.LocalTrack>>;

export function GetRecentAlbums():Promise<Array<desktop.RecentAlbum>>;

export function GetRecentPlaylists():Promise<Array<desktop.RecentPlaylist>>;

export function GetServerURL():Promise<string>;

export function GetToken():Promise<string>;

export function IsConnected():Promise<boolean>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenLocalFiles():Promise<Array<string>>;

export function OpenLocalFolder():Promise<Array<string>>;

export function PickPlaylistArtwork(arg1:string):Promise<string>;

export function ResolvePlaylistItems(arg1:string):Promise<Array<desktop.LocalPlaylistItem>>;

export function RestoreSession(arg1:string,arg2:string):Promise<void>;

export function ScanLocalFolderStream(arg1:string):Promise<void>;

export function SearchLocalTracks(arg1:Array<string>,arg2:string):Promise<Array<desktop.LocalTrack>>;

export function SecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function SetLocalPlaylistItems(arg1:string,arg2:Array<desktop.LocalPlaylistItem>):Promise<void>;

export function SetRecentAlbum(arg1:desktop.RecentAlbum):Promise<void>;

export function SetRecentPlaylist(arg1:desktop.RecentPlaylist):Promise<void>;

export function UnwatchLocalFolder(arg1:string):Promise<void>;

export function UpdateLocalPlaylist(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UploadLocalFile(arg1:string):Promise<string>;

export function UploadPlaylistToServer(arg1:string):Promise<string>;

export function WatchLocalFolder(arg1:string):Promise<void>;
