// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {options} from '../models';

export function AppDBDelete(arg1:string):Promise<void>;

export function AppDBGet(arg1:string):Promise<string>;

export function AppDBSet(arg1:string,arg2:string):Promise<void>;

export function ChooseLocalFolder():Promise<string>;

export function ClearArtworkCache():Promise<void>;

export function ClearLocalFolder(arg1:string):Promise<void>;

export function ConnectToServer(arg1:string,arg2:string,arg3:string):Promise<desktop.ConnectResult>;

export function DisconnectFromServer():Promise<void>;

export function FindLocalDuplicates(arg1:Array<string>):Promise<Array<desktop.LocalDuplicateGroup>>;

export function GetLocalAlbumGroups(arg1:Array<string>,arg2:string,arg3:number,arg4:number):Promise<desktop.LocalAlbumGroupsResult>;

export function GetLocalAlbumTracks(arg1:Array<string>,arg2:string,arg3:string):Promise<Array<desktop.LocalTrack>>;

export function GetLocalPort():Promise<number>;

export function GetLocalTracks(arg1:Array<string>):Promise<Array<desktop.LocalTrack>>;

export function GetLocalTracksByPaths(arg1:Array<string>):Promise<Array<desktop.LocalTrack>>;

export function GetLocalTracksPage(arg1:Array<string>,arg2:number,arg3:number):Promise<Array<desktop.LocalTrack>>;

export function GetServerURL():Promise<string>;

export function GetToken():Promise<string>;

export function IsConnected():Promise<boolean>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenLocalFiles():Promise<Array<string>>;

export function OpenLocalFolder():Promise<Array<string>>;

export function RestoreSession(arg1:string,arg2:string):Promise<void>;

export function ScanLocalFolderStream(arg1:string):Promise<void>;

export function SearchLocalTracks(arg1:Array<string>,arg2:string):Promise<Array<desktop.LocalTrack>>;

export function SecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function UploadLocalFile(arg1:string):Promise<string>;
