// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLocalPlaylistItem(arg1, arg2) {
  return window['go']['desktop']['App']['AddLocalPlaylistItem'](arg1, arg2);
}

export function ChooseLocalFolder() {
  return window['go']['desktop']['App']['ChooseLocalFolder']();
}

export function ClearAllRecent() {
  return window['go']['desktop']['App']['ClearAllRecent']();
}

export function ClearArtworkCache() {
  return window['go']['desktop']['App']['ClearArtworkCache']();
}

export function ClearLocalFolder(arg1) {
  return window['go']['desktop']['App']['ClearLocalFolder'](arg1);
}

export function ConnectToServer(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['ConnectToServer'](arg1, arg2, arg3);
}

export function CreateLocalPlaylist(arg1, arg2) {
  return window['go']['desktop']['App']['CreateLocalPlaylist'](arg1, arg2);
}

export function DeleteLocalPlaylist(arg1) {
  return window['go']['desktop']['App']['DeleteLocalPlaylist'](arg1);
}

export function DisconnectFromServer() {
  return window['go']['desktop']['App']['DisconnectFromServer']();
}

export function GetLocalAlbumGroups(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['GetLocalAlbumGroups'](arg1, arg2, arg3, arg4);
}

export function GetLocalAlbumTracks(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['GetLocalAlbumTracks'](arg1, arg2, arg3);
}

export function GetLocalPlaylistItems(arg1) {
  return window['go']['desktop']['App']['GetLocalPlaylistItems'](arg1);
}

export function GetLocalPlaylists() {
  return window['go']['desktop']['App']['GetLocalPlaylists']();
}

export function GetLocalPort() {
  return window['go']['desktop']['App']['GetLocalPort']();
}

export function GetLocalTracks(arg1) {
  return window['go']['desktop']['App']['GetLocalTracks'](arg1);
}

export function GetLocalTracksByPaths(arg1) {
  return window['go']['desktop']['App']['GetLocalTracksByPaths'](arg1);
}

export function GetLocalTracksPage(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['GetLocalTracksPage'](arg1, arg2, arg3);
}

export function GetRecentAlbums() {
  return window['go']['desktop']['App']['GetRecentAlbums']();
}

export function GetRecentPlaylists() {
  return window['go']['desktop']['App']['GetRecentPlaylists']();
}

export function GetServerURL() {
  return window['go']['desktop']['App']['GetServerURL']();
}

export function GetToken() {
  return window['go']['desktop']['App']['GetToken']();
}

export function IsConnected() {
  return window['go']['desktop']['App']['IsConnected']();
}

export function Notify(arg1, arg2) {
  return window['go']['desktop']['App']['Notify'](arg1, arg2);
}

export function OpenLocalFiles() {
  return window['go']['desktop']['App']['OpenLocalFiles']();
}

export function OpenLocalFolder() {
  return window['go']['desktop']['App']['OpenLocalFolder']();
}

export function PickPlaylistArtwork(arg1) {
  return window['go']['desktop']['App']['PickPlaylistArtwork'](arg1);
}

export function ResolvePlaylistItems(arg1) {
  return window['go']['desktop']['App']['ResolvePlaylistItems'](arg1);
}

export function RestoreSession(arg1, arg2) {
  return window['go']['desktop']['App']['RestoreSession'](arg1, arg2);
}

export function ScanLocalFolderStream(arg1) {
  return window['go']['desktop']['App']['ScanLocalFolderStream'](arg1);
}

export function SearchLocalTracks(arg1, arg2) {
  return window['go']['desktop']['App']['SearchLocalTracks'](arg1, arg2);
}

export function SecondInstanceLaunch(arg1) {
  return window['go']['desktop']['App']['SecondInstanceLaunch'](arg1);
}

export function SetLocalPlaylistItems(arg1, arg2) {
  return window['go']['desktop']['App']['SetLocalPlaylistItems'](arg1, arg2);
}

export function SetRecentAlbum(arg1) {
  return window['go']['desktop']['App']['SetRecentAlbum'](arg1);
}

export function SetRecentPlaylist(arg1) {
  return window['go']['desktop']['App']['SetRecentPlaylist'](arg1);
}

export function UnwatchLocalFolder(arg1) {
  return window['go']['desktop']['App']['UnwatchLocalFolder'](arg1);
}

export function UpdateLocalPlaylist(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['UpdateLocalPlaylist'](arg1, arg2, arg3, arg4);
}

export function UploadLocalFile(arg1) {
  return window['go']['desktop']['App']['UploadLocalFile'](arg1);
}

export function UploadPlaylistToServer(arg1) {
  return window['go']['desktop']['App']['UploadPlaylistToServer'](arg1);
}

export function WatchLocalFolder(arg1) {
  return window['go']['desktop']['App']['WatchLocalFolder'](arg1);
}
