// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kv.sql

package desktopdb

import (
	"context"
)

const deleteKV = `-- name: DeleteKV :exec
DELETE FROM kv WHERE key = ?
`

func (q *Queries) DeleteKV(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteKV, key)
	return err
}

const getKV = `-- name: GetKV :one
SELECT value FROM kv WHERE key = ?
`

func (q *Queries) GetKV(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getKV, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setKV = `-- name: SetKV :exec
INSERT INTO kv (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetKVParams struct {
	Key   string
	Value string
}

func (q *Queries) SetKV(ctx context.Context, arg SetKVParams) error {
	_, err := q.db.ExecContext(ctx, setKV, arg.Key, arg.Value)
	return err
}
