// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: local_tracks.sql

package desktopdb

import (
	"context"
	"strings"
)

const allLocalTracksPage = `-- name: AllLocalTracksPage :many
SELECT path, folder, title, artist, album, album_artist, genre,
       year, track_number, disc_number, duration_ms, has_artwork
FROM local_tracks
ORDER BY album COLLATE NOCASE, disc_number, track_number
LIMIT ? OFFSET ?
`

type AllLocalTracksPageParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) AllLocalTracksPage(ctx context.Context, arg AllLocalTracksPageParams) ([]LocalTrack, error) {
	rows, err := q.db.QueryContext(ctx, allLocalTracksPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalTrack
	for rows.Next() {
		var i LocalTrack
		if err := rows.Scan(
			&i.Path,
			&i.Folder,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.AlbumArtist,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.HasArtwork,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAllLocalTracks = `-- name: CountAllLocalTracks :one
SELECT COUNT(*) FROM local_tracks
`

func (q *Queries) CountAllLocalTracks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllLocalTracks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLocalTrackByPath = `-- name: DeleteLocalTrackByPath :exec
DELETE FROM local_tracks WHERE path = ?
`

func (q *Queries) DeleteLocalTrackByPath(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteLocalTrackByPath, path)
	return err
}

const deleteLocalTracksByFolder = `-- name: DeleteLocalTracksByFolder :exec
DELETE FROM local_tracks WHERE folder = ?
`

func (q *Queries) DeleteLocalTracksByFolder(ctx context.Context, folder string) error {
	_, err := q.db.ExecContext(ctx, deleteLocalTracksByFolder, folder)
	return err
}

const deleteLocalTracksByPathPrefix = `-- name: DeleteLocalTracksByPathPrefix :execrows
DELETE FROM local_tracks WHERE path = ? OR path LIKE ?
`

type DeleteLocalTracksByPathPrefixParams struct {
	Path   string
	Path_2 string
}

func (q *Queries) DeleteLocalTracksByPathPrefix(ctx context.Context, arg DeleteLocalTracksByPathPrefixParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLocalTracksByPathPrefix, arg.Path, arg.Path_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLocalTracksByPaths = `-- name: DeleteLocalTracksByPaths :execrows
DELETE FROM local_tracks
WHERE path IN (/*SLICE:paths*/?)
`

func (q *Queries) DeleteLocalTracksByPaths(ctx context.Context, paths []string) (int64, error) {
	query := deleteLocalTracksByPaths
	var queryParams []interface{}
	if len(paths) > 0 {
		for _, v := range paths {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:paths*/?", strings.Repeat(",?", len(paths))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:paths*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAllLocalTracks = `-- name: ListAllLocalTracks :many
SELECT path, folder, title, artist, album, album_artist, genre,
       year, track_number, disc_number, duration_ms, has_artwork
FROM local_tracks
ORDER BY folder, path
`

func (q *Queries) ListAllLocalTracks(ctx context.Context) ([]LocalTrack, error) {
	rows, err := q.db.QueryContext(ctx, listAllLocalTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalTrack
	for rows.Next() {
		var i LocalTrack
		if err := rows.Scan(
			&i.Path,
			&i.Folder,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.AlbumArtist,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.HasArtwork,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalTracksByPaths = `-- name: ListLocalTracksByPaths :many
SELECT path, folder, title, artist, album, album_artist, genre,
       year, track_number, disc_number, duration_ms, has_artwork
FROM local_tracks
WHERE path IN (/*SLICE:paths*/?)
`

func (q *Queries) ListLocalTracksByPaths(ctx context.Context, paths []string) ([]LocalTrack, error) {
	query := listLocalTracksByPaths
	var queryParams []interface{}
	if len(paths) > 0 {
		for _, v := range paths {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:paths*/?", strings.Repeat(",?", len(paths))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:paths*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalTrack
	for rows.Next() {
		var i LocalTrack
		if err := rows.Scan(
			&i.Path,
			&i.Folder,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.AlbumArtist,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.HasArtwork,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPathsByFolder = `-- name: ListPathsByFolder :many
SELECT path FROM local_tracks WHERE folder = ?
`

func (q *Queries) ListPathsByFolder(ctx context.Context, folder string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPathsByFolder, folder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAllLocalTracks = `-- name: SearchAllLocalTracks :many
SELECT path, folder, title, artist, album, album_artist, genre,
       year, track_number, disc_number, duration_ms, has_artwork
FROM local_tracks
WHERE title LIKE ? OR artist LIKE ? OR album LIKE ? OR path LIKE ?
ORDER BY title COLLATE NOCASE
LIMIT 50
`

type SearchAllLocalTracksParams struct {
	Title  string
	Artist string
	Album  string
	Path   string
}

func (q *Queries) SearchAllLocalTracks(ctx context.Context, arg SearchAllLocalTracksParams) ([]LocalTrack, error) {
	rows, err := q.db.QueryContext(ctx, searchAllLocalTracks,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.Path,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalTrack
	for rows.Next() {
		var i LocalTrack
		if err := rows.Scan(
			&i.Path,
			&i.Folder,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.AlbumArtist,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.HasArtwork,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLocalTrack = `-- name: UpsertLocalTrack :exec
INSERT INTO local_tracks (
    path, folder, title, artist, album, album_artist, genre,
    year, track_number, disc_number, duration_ms, has_artwork
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(path) DO UPDATE SET
    folder       = excluded.folder,
    title        = excluded.title,
    artist       = excluded.artist,
    album        = excluded.album,
    album_artist = excluded.album_artist,
    genre        = excluded.genre,
    year         = excluded.year,
    track_number = excluded.track_number,
    disc_number  = excluded.disc_number,
    duration_ms  = excluded.duration_ms,
    has_artwork  = excluded.has_artwork
`

type UpsertLocalTrackParams struct {
	Path        string
	Folder      string
	Title       string
	Artist      string
	Album       string
	AlbumArtist string
	Genre       string
	Year        int64
	TrackNumber int64
	DiscNumber  int64
	DurationMs  int64
	HasArtwork  bool
}

func (q *Queries) UpsertLocalTrack(ctx context.Context, arg UpsertLocalTrackParams) error {
	_, err := q.db.ExecContext(ctx, upsertLocalTrack,
		arg.Path,
		arg.Folder,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.AlbumArtist,
		arg.Genre,
		arg.Year,
		arg.TrackNumber,
		arg.DiscNumber,
		arg.DurationMs,
		arg.HasArtwork,
	)
	return err
}
