// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package desktopdb

import (
	"database/sql"
)

type LocalPlaylist struct {
	ID               string
	Name             string
	Description      string
	ArtworkPath      string
	RemotePlaylistID string
	CreatedAt        string
	UpdatedAt        string
}

type LocalPlaylistItem struct {
	PlaylistID     string
	Position       int64
	Source         string
	TrackID        string
	LocalPath      string
	RefTitle       string
	RefAlbum       string
	RefAlbumArtist string
	RefDurationMs  int64
	AddedAt        string
}

type LocalTrack struct {
	Path        string
	Folder      string
	Title       string
	Artist      string
	Album       string
	AlbumArtist string
	Genre       string
	Year        int64
	TrackNumber int64
	DiscNumber  int64
	DurationMs  int64
	HasArtwork  bool
}

type PlaybackSession struct {
	ID         string
	TrackID    sql.NullString
	PositionMs sql.NullInt64
	QueueJson  sql.NullString
	QueueIndex sql.NullInt64
	RepeatMode sql.NullInt64
	Shuffle    bool
	Playing    bool
	UpdatedAt  string
}

type RecentAlbum struct {
	Key            string
	Name           string
	Artist         string
	IsLocal        bool
	FirstTrackID   sql.NullString
	FirstLocalPath sql.NullString
	PlayedAt       int64
}

type RecentPlaylist struct {
	ID          string
	Name        string
	ArtworkPath sql.NullString
	PlayedAt    int64
}
