// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package desktopdb

type Kv struct {
	Key   string
	Value string
}

type LocalTrack struct {
	Path        string
	Folder      string
	Title       string
	Artist      string
	Album       string
	AlbumArtist string
	Genre       string
	Year        int64
	TrackNumber int64
	DiscNumber  int64
	DurationMs  int64
	HasArtwork  int64
}
