// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlists.sql

package desktopdb

import (
	"context"
)

const countLocalPlaylistItems = `-- name: CountLocalPlaylistItems :one
SELECT COUNT(*) FROM local_playlist_items WHERE playlist_id = ?
`

func (q *Queries) CountLocalPlaylistItems(ctx context.Context, playlistID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLocalPlaylistItems, playlistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocalPlaylist = `-- name: CreateLocalPlaylist :exec
INSERT INTO local_playlists (id, name, description, artwork_path, remote_playlist_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateLocalPlaylistParams struct {
	ID               string
	Name             string
	Description      string
	ArtworkPath      string
	RemotePlaylistID string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateLocalPlaylist(ctx context.Context, arg CreateLocalPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, createLocalPlaylist,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ArtworkPath,
		arg.RemotePlaylistID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteLocalPlaylist = `-- name: DeleteLocalPlaylist :exec
DELETE FROM local_playlists WHERE id = ?
`

func (q *Queries) DeleteLocalPlaylist(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLocalPlaylist, id)
	return err
}

const deleteLocalPlaylistItems = `-- name: DeleteLocalPlaylistItems :exec
DELETE FROM local_playlist_items WHERE playlist_id = ?
`

func (q *Queries) DeleteLocalPlaylistItems(ctx context.Context, playlistID string) error {
	_, err := q.db.ExecContext(ctx, deleteLocalPlaylistItems, playlistID)
	return err
}

const getLocalPlaylistByID = `-- name: GetLocalPlaylistByID :one
SELECT id, name, description, artwork_path, remote_playlist_id, created_at, updated_at
FROM local_playlists WHERE id = ?
`

func (q *Queries) GetLocalPlaylistByID(ctx context.Context, id string) (LocalPlaylist, error) {
	row := q.db.QueryRowContext(ctx, getLocalPlaylistByID, id)
	var i LocalPlaylist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ArtworkPath,
		&i.RemotePlaylistID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocalPlaylistByRemoteID = `-- name: GetLocalPlaylistByRemoteID :one
SELECT id, name, description, artwork_path, remote_playlist_id, created_at, updated_at
FROM local_playlists WHERE remote_playlist_id = ? LIMIT 1
`

func (q *Queries) GetLocalPlaylistByRemoteID(ctx context.Context, remotePlaylistID string) (LocalPlaylist, error) {
	row := q.db.QueryRowContext(ctx, getLocalPlaylistByRemoteID, remotePlaylistID)
	var i LocalPlaylist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ArtworkPath,
		&i.RemotePlaylistID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLocalPlaylistItem = `-- name: InsertLocalPlaylistItem :exec
INSERT INTO local_playlist_items (playlist_id, position, source, track_id, local_path, ref_title, ref_album, ref_album_artist, ref_duration_ms, added_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertLocalPlaylistItemParams struct {
	PlaylistID     string
	Position       int64
	Source         string
	TrackID        string
	LocalPath      string
	RefTitle       string
	RefAlbum       string
	RefAlbumArtist string
	RefDurationMs  int64
	AddedAt        string
}

func (q *Queries) InsertLocalPlaylistItem(ctx context.Context, arg InsertLocalPlaylistItemParams) error {
	_, err := q.db.ExecContext(ctx, insertLocalPlaylistItem,
		arg.PlaylistID,
		arg.Position,
		arg.Source,
		arg.TrackID,
		arg.LocalPath,
		arg.RefTitle,
		arg.RefAlbum,
		arg.RefAlbumArtist,
		arg.RefDurationMs,
		arg.AddedAt,
	)
	return err
}

const listLocalPlaylistItems = `-- name: ListLocalPlaylistItems :many
SELECT playlist_id, position, source, track_id, local_path,
       ref_title, ref_album, ref_album_artist, ref_duration_ms, added_at
FROM local_playlist_items
WHERE playlist_id = ?
ORDER BY position
`

func (q *Queries) ListLocalPlaylistItems(ctx context.Context, playlistID string) ([]LocalPlaylistItem, error) {
	rows, err := q.db.QueryContext(ctx, listLocalPlaylistItems, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalPlaylistItem
	for rows.Next() {
		var i LocalPlaylistItem
		if err := rows.Scan(
			&i.PlaylistID,
			&i.Position,
			&i.Source,
			&i.TrackID,
			&i.LocalPath,
			&i.RefTitle,
			&i.RefAlbum,
			&i.RefAlbumArtist,
			&i.RefDurationMs,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalPlaylists = `-- name: ListLocalPlaylists :many
SELECT lp.id, lp.name, lp.description, lp.artwork_path, lp.remote_playlist_id,
       lp.created_at, lp.updated_at,
       COUNT(li.playlist_id) AS item_count,
       CAST(COALESCE(SUM(CASE
           WHEN li.source = 'local_ref' THEN li.ref_duration_ms
           ELSE li.ref_duration_ms
       END), 0) AS INTEGER) AS total_duration_ms
FROM local_playlists lp
LEFT JOIN local_playlist_items li ON li.playlist_id = lp.id
GROUP BY lp.id
ORDER BY lp.updated_at DESC
`

type ListLocalPlaylistsRow struct {
	ID               string
	Name             string
	Description      string
	ArtworkPath      string
	RemotePlaylistID string
	CreatedAt        string
	UpdatedAt        string
	ItemCount        int64
	TotalDurationMs  int64
}

func (q *Queries) ListLocalPlaylists(ctx context.Context) ([]ListLocalPlaylistsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLocalPlaylists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocalPlaylistsRow
	for rows.Next() {
		var i ListLocalPlaylistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ArtworkPath,
			&i.RemotePlaylistID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemCount,
			&i.TotalDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchLocalPlaylist = `-- name: TouchLocalPlaylist :exec
UPDATE local_playlists SET updated_at = ? WHERE id = ?
`

type TouchLocalPlaylistParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) TouchLocalPlaylist(ctx context.Context, arg TouchLocalPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, touchLocalPlaylist, arg.UpdatedAt, arg.ID)
	return err
}

const updateLocalPlaylist = `-- name: UpdateLocalPlaylist :exec
UPDATE local_playlists SET name = ?, description = ?, artwork_path = ?, remote_playlist_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateLocalPlaylistParams struct {
	Name             string
	Description      string
	ArtworkPath      string
	RemotePlaylistID string
	UpdatedAt        string
	ID               string
}

func (q *Queries) UpdateLocalPlaylist(ctx context.Context, arg UpdateLocalPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, updateLocalPlaylist,
		arg.Name,
		arg.Description,
		arg.ArtworkPath,
		arg.RemotePlaylistID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateLocalPlaylistArtwork = `-- name: UpdateLocalPlaylistArtwork :exec
UPDATE local_playlists SET artwork_path = ?, updated_at = ?
WHERE id = ?
`

type UpdateLocalPlaylistArtworkParams struct {
	ArtworkPath string
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateLocalPlaylistArtwork(ctx context.Context, arg UpdateLocalPlaylistArtworkParams) error {
	_, err := q.db.ExecContext(ctx, updateLocalPlaylistArtwork, arg.ArtworkPath, arg.UpdatedAt, arg.ID)
	return err
}
