// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playback_session.sql

package desktopdb

import (
	"context"
	"database/sql"
)

const getPlaybackSession = `-- name: GetPlaybackSession :one
SELECT
    COALESCE(track_id, '') AS track_id,
    position_ms, queue_json, queue_index, repeat_mode, shuffle, playing, updated_at
FROM playback_session WHERE id = 'current' LIMIT 1
`

type GetPlaybackSessionRow struct {
	TrackID    string
	PositionMs sql.NullInt64
	QueueJson  sql.NullString
	QueueIndex sql.NullInt64
	RepeatMode sql.NullInt64
	Shuffle    sql.NullInt64
	Playing    sql.NullInt64
	UpdatedAt  string
}

func (q *Queries) GetPlaybackSession(ctx context.Context) (GetPlaybackSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getPlaybackSession)
	var i GetPlaybackSessionRow
	err := row.Scan(
		&i.TrackID,
		&i.PositionMs,
		&i.QueueJson,
		&i.QueueIndex,
		&i.RepeatMode,
		&i.Shuffle,
		&i.Playing,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlaybackSession = `-- name: UpsertPlaybackSession :exec
INSERT INTO playback_session (
    track_id, position_ms, queue_json, queue_index, repeat_mode, shuffle, playing, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    track_id = excluded.track_id, position_ms = excluded.position_ms,
    queue_json = excluded.queue_json, queue_index = excluded.queue_index,
    repeat_mode = excluded.repeat_mode, shuffle = excluded.shuffle,
    playing = excluded.playing, updated_at = excluded.updated_at
`

type UpsertPlaybackSessionParams struct {
	TrackID    sql.NullString
	PositionMs sql.NullInt64
	QueueJson  sql.NullString
	QueueIndex sql.NullInt64
	RepeatMode sql.NullInt64
	Shuffle    sql.NullInt64
	Playing    sql.NullInt64
	UpdatedAt  string
}

func (q *Queries) UpsertPlaybackSession(ctx context.Context, arg UpsertPlaybackSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlaybackSession,
		arg.TrackID,
		arg.PositionMs,
		arg.QueueJson,
		arg.QueueIndex,
		arg.RepeatMode,
		arg.Shuffle,
		arg.Playing,
		arg.UpdatedAt,
	)
	return err
}
