// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recent.sql

package desktopdb

import (
	"context"
	"database/sql"
)

const deleteRecentAlbum = `-- name: DeleteRecentAlbum :exec
DELETE FROM recent_albums WHERE key = ?
`

func (q *Queries) DeleteRecentAlbum(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteRecentAlbum, key)
	return err
}

const deleteRecentPlaylist = `-- name: DeleteRecentPlaylist :exec
DELETE FROM recent_playlists WHERE id = ?
`

func (q *Queries) DeleteRecentPlaylist(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRecentPlaylist, id)
	return err
}

const getRecentAlbum = `-- name: GetRecentAlbum :one
SELECT key, name, artist, is_local, first_track_id, first_local_path, played_at 
FROM recent_albums 
WHERE key = ?
`

func (q *Queries) GetRecentAlbum(ctx context.Context, key string) (RecentAlbum, error) {
	row := q.db.QueryRowContext(ctx, getRecentAlbum, key)
	var i RecentAlbum
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.Artist,
		&i.IsLocal,
		&i.FirstTrackID,
		&i.FirstLocalPath,
		&i.PlayedAt,
	)
	return i, err
}

const getRecentAlbums = `-- name: GetRecentAlbums :many
SELECT key, name, artist, is_local, first_track_id, first_local_path, played_at 
FROM recent_albums 
ORDER BY played_at DESC
`

func (q *Queries) GetRecentAlbums(ctx context.Context) ([]RecentAlbum, error) {
	rows, err := q.db.QueryContext(ctx, getRecentAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentAlbum
	for rows.Next() {
		var i RecentAlbum
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Artist,
			&i.IsLocal,
			&i.FirstTrackID,
			&i.FirstLocalPath,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentPlaylist = `-- name: GetRecentPlaylist :one
SELECT id, name, artwork_path, played_at 
FROM recent_playlists 
WHERE id = ?
`

func (q *Queries) GetRecentPlaylist(ctx context.Context, id string) (RecentPlaylist, error) {
	row := q.db.QueryRowContext(ctx, getRecentPlaylist, id)
	var i RecentPlaylist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArtworkPath,
		&i.PlayedAt,
	)
	return i, err
}

const getRecentPlaylists = `-- name: GetRecentPlaylists :many
SELECT id, name, artwork_path, played_at 
FROM recent_playlists 
ORDER BY played_at DESC
`

func (q *Queries) GetRecentPlaylists(ctx context.Context) ([]RecentPlaylist, error) {
	rows, err := q.db.QueryContext(ctx, getRecentPlaylists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentPlaylist
	for rows.Next() {
		var i RecentPlaylist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ArtworkPath,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRecentAlbum = `-- name: SetRecentAlbum :exec
INSERT INTO recent_albums (key, name, artist, is_local, first_track_id, first_local_path, played_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(key) DO UPDATE SET
    name = excluded.name,
    artist = excluded.artist,
    is_local = excluded.is_local,
    first_track_id = excluded.first_track_id,
    first_local_path = excluded.first_local_path,
    played_at = excluded.played_at
`

type SetRecentAlbumParams struct {
	Key            string
	Name           string
	Artist         string
	IsLocal        int64
	FirstTrackID   sql.NullString
	FirstLocalPath sql.NullString
	PlayedAt       int64
}

func (q *Queries) SetRecentAlbum(ctx context.Context, arg SetRecentAlbumParams) error {
	_, err := q.db.ExecContext(ctx, setRecentAlbum,
		arg.Key,
		arg.Name,
		arg.Artist,
		arg.IsLocal,
		arg.FirstTrackID,
		arg.FirstLocalPath,
		arg.PlayedAt,
	)
	return err
}

const setRecentPlaylist = `-- name: SetRecentPlaylist :exec
INSERT INTO recent_playlists (id, name, artwork_path, played_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    artwork_path = excluded.artwork_path,
    played_at = excluded.played_at
`

type SetRecentPlaylistParams struct {
	ID          string
	Name        string
	ArtworkPath sql.NullString
	PlayedAt    int64
}

func (q *Queries) SetRecentPlaylist(ctx context.Context, arg SetRecentPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, setRecentPlaylist,
		arg.ID,
		arg.Name,
		arg.ArtworkPath,
		arg.PlayedAt,
	)
	return err
}
