# mainly for testing before production
# use tailscale to serve the staging instance to tailnet for testing in https environment
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: pneuma:staging
    restart: unless-stopped
    environment:
      PNEUMA_SERVER_HOST: 0.0.0.0
      PNEUMA_SERVER_PORT: 8989
      PNEUMA_DATA_DIR: /data
      PNEUMA_LIBRARY_SCAN_INTERVAL_MINUTES: 120
      PNEUMA_TRANSCODING_CACHE_MAX_SIZE_MB: 2048
      PNEUMA_TRANSCODING_MAX_CONCURRENT_JOBS: 1
    volumes:
      - pneuma_staging_data:/data
    ports:
      - "8989:8989"

volumes:
  pneuma_staging_data:
