// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package serverdb

import (
	"context"
	"database/sql"
)

const clearAuditEntries = `-- name: ClearAuditEntries :exec
DELETE FROM audit_log
`

func (q *Queries) ClearAuditEntries(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAuditEntries)
	return err
}

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_log (
    id, user_id, action, target_type, target_id, detail, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditEntryParams struct {
	ID         string
	UserID     string
	Action     string
	TargetType string
	TargetID   string
	Detail     sql.NullString
	CreatedAt  string
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEntry,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Detail,
		arg.CreatedAt,
	)
	return err
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT
    id,
    user_id,
    action,
    target_type,
    target_id,
    detail,
    created_at
FROM audit_log
ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListAuditEntries(ctx context.Context, limit int64) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
