// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package serverdb

import (
	"context"
)

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, name, created_at, last_active
FROM devices
WHERE id = ? LIMIT 1
`

func (q *Queries) GetDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.LastActive,
	)
	return i, err
}

const listUserDevices = `-- name: ListUserDevices :many
SELECT id, user_id, name, created_at, last_active
FROM devices
WHERE user_id = ?
ORDER BY last_active DESC
`

func (q *Queries) ListUserDevices(ctx context.Context, userID string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listUserDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.LastActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :exec

INSERT INTO devices (
    id, user_id, name, created_at, last_active
) VALUES ( ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name,
    last_active = excluded.last_active
`

type UpsertDeviceParams struct {
	ID         string
	UserID     string
	Name       string
	CreatedAt  string
	LastActive string
}

// Keep the "name" field in here in case there are feature requests for device management
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertDevice,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.CreatedAt,
		arg.LastActive,
	)
	return err
}
