// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package serverdb

import (
	"context"
	"database/sql"
)

const devicesByUser = `-- name: DevicesByUser :many
SELECT
    id,
    user_id,
    name,
    last_seen_at,
    created_at
FROM devices
WHERE user_id = ?
ORDER BY last_seen_at DESC
`

func (q *Queries) DevicesByUser(ctx context.Context, userID string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, devicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices SET last_seen_at = ?
WHERE id = ?
`

type TouchDeviceParams struct {
	LastSeenAt sql.NullString
	ID         string
}

func (q *Queries) TouchDevice(ctx context.Context, arg TouchDeviceParams) error {
	_, err := q.db.ExecContext(ctx, touchDevice, arg.LastSeenAt, arg.ID)
	return err
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO devices (id, user_id, name, last_seen_at, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name, last_seen_at = excluded.last_seen_at
`

type UpsertDeviceParams struct {
	ID         string
	UserID     string
	Name       string
	LastSeenAt sql.NullString
	CreatedAt  string
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertDevice,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.LastSeenAt,
		arg.CreatedAt,
	)
	return err
}
