// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: disk_usage.sql

package serverdb

import (
	"context"
)

const getLatestDiskUsage = `-- name: GetLatestDiskUsage :one
SELECT
    id, total_bytes, free_bytes, tracks_bytes, db_bytes,
    transcode_cache_bytes, artwork_cache_bytes, playlist_art_bytes, recorded_at
FROM disk_usage
ORDER BY recorded_at DESC
LIMIT 1
`

func (q *Queries) GetLatestDiskUsage(ctx context.Context) (DiskUsage, error) {
	row := q.db.QueryRowContext(ctx, getLatestDiskUsage)
	var i DiskUsage
	err := row.Scan(
		&i.ID,
		&i.TotalBytes,
		&i.FreeBytes,
		&i.TracksBytes,
		&i.DbBytes,
		&i.TranscodeCacheBytes,
		&i.ArtworkCacheBytes,
		&i.PlaylistArtBytes,
		&i.RecordedAt,
	)
	return i, err
}

const insertDiskUsage = `-- name: InsertDiskUsage :exec
INSERT INTO disk_usage (
    id, total_bytes, free_bytes, tracks_bytes, db_bytes,
    transcode_cache_bytes, artwork_cache_bytes, playlist_art_bytes, recorded_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDiskUsageParams struct {
	ID                  string
	TotalBytes          int64
	FreeBytes           int64
	TracksBytes         int64
	DbBytes             int64
	TranscodeCacheBytes int64
	ArtworkCacheBytes   int64
	PlaylistArtBytes    int64
	RecordedAt          string
}

func (q *Queries) InsertDiskUsage(ctx context.Context, arg InsertDiskUsageParams) error {
	_, err := q.db.ExecContext(ctx, insertDiskUsage,
		arg.ID,
		arg.TotalBytes,
		arg.FreeBytes,
		arg.TracksBytes,
		arg.DbBytes,
		arg.TranscodeCacheBytes,
		arg.ArtworkCacheBytes,
		arg.PlaylistArtBytes,
		arg.RecordedAt,
	)
	return err
}

const pruneDiskUsageHistory = `-- name: PruneDiskUsageHistory :exec
DELETE FROM disk_usage
WHERE id NOT IN (
    SELECT id FROM disk_usage ORDER BY recorded_at DESC LIMIT ?
)
`

func (q *Queries) PruneDiskUsageHistory(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, pruneDiskUsageHistory, limit)
	return err
}
