// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: library.sql

package serverdb

import (
	"context"
	"database/sql"
)

const albumByID = `-- name: AlbumByID :one
SELECT id, title, COALESCE(artist_id,'') AS artist_id, year,
    COALESCE(mb_release_id,'') AS mb_release_id, COALESCE(artwork_id,'') AS artwork_id, created_at
FROM albums WHERE id = ?
`

type AlbumByIDRow struct {
	ID          string
	Title       string
	ArtistID    string
	Year        sql.NullInt64
	MbReleaseID string
	ArtworkID   string
	CreatedAt   string
}

func (q *Queries) AlbumByID(ctx context.Context, id string) (AlbumByIDRow, error) {
	row := q.db.QueryRowContext(ctx, albumByID, id)
	var i AlbumByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ArtistID,
		&i.Year,
		&i.MbReleaseID,
		&i.ArtworkID,
		&i.CreatedAt,
	)
	return i, err
}

const albumByTitleArtist = `-- name: AlbumByTitleArtist :one
SELECT id, title, COALESCE(artist_id,'') AS artist_id, year,
    COALESCE(mb_release_id,'') AS mb_release_id, COALESCE(artwork_id,'') AS artwork_id, created_at
FROM albums WHERE title = ? AND COALESCE(artist_id,'') = ? LIMIT 1
`

type AlbumByTitleArtistParams struct {
	Title    string
	ArtistID sql.NullString
}

type AlbumByTitleArtistRow struct {
	ID          string
	Title       string
	ArtistID    string
	Year        sql.NullInt64
	MbReleaseID string
	ArtworkID   string
	CreatedAt   string
}

func (q *Queries) AlbumByTitleArtist(ctx context.Context, arg AlbumByTitleArtistParams) (AlbumByTitleArtistRow, error) {
	row := q.db.QueryRowContext(ctx, albumByTitleArtist, arg.Title, arg.ArtistID)
	var i AlbumByTitleArtistRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ArtistID,
		&i.Year,
		&i.MbReleaseID,
		&i.ArtworkID,
		&i.CreatedAt,
	)
	return i, err
}

const artistByName = `-- name: ArtistByName :one
SELECT id, name, COALESCE(mb_artist_id,'') AS mb_artist_id, created_at
FROM artists WHERE name = ? LIMIT 1
`

type ArtistByNameRow struct {
	ID         string
	Name       string
	MbArtistID string
	CreatedAt  string
}

func (q *Queries) ArtistByName(ctx context.Context, name string) (ArtistByNameRow, error) {
	row := q.db.QueryRowContext(ctx, artistByName, name)
	var i ArtistByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MbArtistID,
		&i.CreatedAt,
	)
	return i, err
}

const artworkByPath = `-- name: ArtworkByPath :one
SELECT id, path, COALESCE(width,0) AS width, COALESCE(height,0) AS height,
    COALESCE(format,'') AS format, created_at
FROM artworks WHERE path = ? LIMIT 1
`

type ArtworkByPathRow struct {
	ID        string
	Path      string
	Width     int64
	Height    int64
	Format    string
	CreatedAt string
}

func (q *Queries) ArtworkByPath(ctx context.Context, path string) (ArtworkByPathRow, error) {
	row := q.db.QueryRowContext(ctx, artworkByPath, path)
	var i ArtworkByPathRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Width,
		&i.Height,
		&i.Format,
		&i.CreatedAt,
	)
	return i, err
}

const countAlbums = `-- name: CountAlbums :one
SELECT COUNT(*) FROM albums
`

func (q *Queries) CountAlbums(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAlbums)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAlbumsFiltered = `-- name: CountAlbumsFiltered :one
SELECT COUNT(*) FROM albums WHERE title LIKE ?
`

func (q *Queries) CountAlbumsFiltered(ctx context.Context, title string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAlbumsFiltered, title)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAlbums = `-- name: ListAlbums :many
SELECT id, title, COALESCE(artist_id,'') AS artist_id, year,
    COALESCE(mb_release_id,'') AS mb_release_id, COALESCE(artwork_id,'') AS artwork_id, created_at
FROM albums ORDER BY title COLLATE NOCASE
`

type ListAlbumsRow struct {
	ID          string
	Title       string
	ArtistID    string
	Year        sql.NullInt64
	MbReleaseID string
	ArtworkID   string
	CreatedAt   string
}

func (q *Queries) ListAlbums(ctx context.Context) ([]ListAlbumsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsRow
	for rows.Next() {
		var i ListAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.Year,
			&i.MbReleaseID,
			&i.ArtworkID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsPage = `-- name: ListAlbumsPage :many
SELECT id, title, COALESCE(artist_id,'') AS artist_id, year,
    COALESCE(mb_release_id,'') AS mb_release_id, COALESCE(artwork_id,'') AS artwork_id, created_at
FROM albums ORDER BY title COLLATE NOCASE LIMIT ? OFFSET ?
`

type ListAlbumsPageParams struct {
	Limit  int64
	Offset int64
}

type ListAlbumsPageRow struct {
	ID          string
	Title       string
	ArtistID    string
	Year        sql.NullInt64
	MbReleaseID string
	ArtworkID   string
	CreatedAt   string
}

func (q *Queries) ListAlbumsPage(ctx context.Context, arg ListAlbumsPageParams) ([]ListAlbumsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsPageRow
	for rows.Next() {
		var i ListAlbumsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.Year,
			&i.MbReleaseID,
			&i.ArtworkID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsPageFiltered = `-- name: ListAlbumsPageFiltered :many
SELECT id, title, COALESCE(artist_id,'') AS artist_id, year,
    COALESCE(mb_release_id,'') AS mb_release_id, COALESCE(artwork_id,'') AS artwork_id, created_at
FROM albums WHERE title LIKE ? ORDER BY title COLLATE NOCASE LIMIT ? OFFSET ?
`

type ListAlbumsPageFilteredParams struct {
	Title  string
	Limit  int64
	Offset int64
}

type ListAlbumsPageFilteredRow struct {
	ID          string
	Title       string
	ArtistID    string
	Year        sql.NullInt64
	MbReleaseID string
	ArtworkID   string
	CreatedAt   string
}

func (q *Queries) ListAlbumsPageFiltered(ctx context.Context, arg ListAlbumsPageFilteredParams) ([]ListAlbumsPageFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsPageFiltered, arg.Title, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsPageFilteredRow
	for rows.Next() {
		var i ListAlbumsPageFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.Year,
			&i.MbReleaseID,
			&i.ArtworkID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchFolders = `-- name: ListWatchFolders :many
SELECT id, path, user_id, created_at FROM watch_folders
`

func (q *Queries) ListWatchFolders(ctx context.Context) ([]WatchFolder, error) {
	rows, err := q.db.QueryContext(ctx, listWatchFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchFolder
	for rows.Next() {
		var i WatchFolder
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAlbum = `-- name: UpsertAlbum :exec
INSERT INTO albums (id, title, artist_id, year, mb_release_id, artwork_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    title=excluded.title, artist_id=excluded.artist_id, year=excluded.year,
    mb_release_id=excluded.mb_release_id, artwork_id=excluded.artwork_id
`

type UpsertAlbumParams struct {
	ID          string
	Title       string
	ArtistID    sql.NullString
	Year        sql.NullInt64
	MbReleaseID sql.NullString
	ArtworkID   sql.NullString
	CreatedAt   string
}

func (q *Queries) UpsertAlbum(ctx context.Context, arg UpsertAlbumParams) error {
	_, err := q.db.ExecContext(ctx, upsertAlbum,
		arg.ID,
		arg.Title,
		arg.ArtistID,
		arg.Year,
		arg.MbReleaseID,
		arg.ArtworkID,
		arg.CreatedAt,
	)
	return err
}

const upsertArtist = `-- name: UpsertArtist :exec
INSERT INTO artists (id, name, mb_artist_id, created_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET name=excluded.name, mb_artist_id=excluded.mb_artist_id
`

type UpsertArtistParams struct {
	ID         string
	Name       string
	MbArtistID sql.NullString
	CreatedAt  string
}

func (q *Queries) UpsertArtist(ctx context.Context, arg UpsertArtistParams) error {
	_, err := q.db.ExecContext(ctx, upsertArtist,
		arg.ID,
		arg.Name,
		arg.MbArtistID,
		arg.CreatedAt,
	)
	return err
}

const upsertArtwork = `-- name: UpsertArtwork :exec
INSERT INTO artworks (id, path, width, height, format, created_at) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(path) DO UPDATE SET width=excluded.width, height=excluded.height, format=excluded.format
`

type UpsertArtworkParams struct {
	ID        string
	Path      string
	Width     sql.NullInt64
	Height    sql.NullInt64
	Format    sql.NullString
	CreatedAt string
}

func (q *Queries) UpsertArtwork(ctx context.Context, arg UpsertArtworkParams) error {
	_, err := q.db.ExecContext(ctx, upsertArtwork,
		arg.ID,
		arg.Path,
		arg.Width,
		arg.Height,
		arg.Format,
		arg.CreatedAt,
	)
	return err
}

const upsertWatchFolder = `-- name: UpsertWatchFolder :exec
INSERT OR IGNORE INTO watch_folders (id, path, user_id, created_at) VALUES (?, ?, ?, ?)
`

type UpsertWatchFolderParams struct {
	ID        string
	Path      string
	UserID    string
	CreatedAt string
}

func (q *Queries) UpsertWatchFolder(ctx context.Context, arg UpsertWatchFolderParams) error {
	_, err := q.db.ExecContext(ctx, upsertWatchFolder,
		arg.ID,
		arg.Path,
		arg.UserID,
		arg.CreatedAt,
	)
	return err
}
