// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: library.sql

package serverdb

import (
	"context"
)

const listWatchFolders = `-- name: ListWatchFolders :many
SELECT id, path, user_id, created_at FROM watch_folders
`

func (q *Queries) ListWatchFolders(ctx context.Context) ([]WatchFolder, error) {
	rows, err := q.db.QueryContext(ctx, listWatchFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchFolder
	for rows.Next() {
		var i WatchFolder
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWatchFolder = `-- name: UpsertWatchFolder :exec
INSERT OR IGNORE INTO watch_folders (id, path, user_id, created_at) VALUES (?, ?, ?, ?)
`

type UpsertWatchFolderParams struct {
	ID        string
	Path      string
	UserID    string
	CreatedAt string
}

func (q *Queries) UpsertWatchFolder(ctx context.Context, arg UpsertWatchFolderParams) error {
	_, err := q.db.ExecContext(ctx, upsertWatchFolder,
		arg.ID,
		arg.Path,
		arg.UserID,
		arg.CreatedAt,
	)
	return err
}
