// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package serverdb

import (
	"database/sql"
)

type AuditLog struct {
	ID         string
	UserID     string
	Action     string
	TargetType string
	TargetID   string
	Detail     sql.NullString
	CreatedAt  string
}

type Device struct {
	ID         string
	UserID     string
	Name       string
	CreatedAt  string
	LastActive string
}

type PlaybackSession struct {
	ID         string
	DeviceID   string
	UserID     string
	TrackID    sql.NullString
	PositionMs sql.NullInt64
	QueueJson  sql.NullString
	QueueIndex sql.NullInt64
	RepeatMode sql.NullInt64
	Shuffle    sql.NullInt64
	Playing    sql.NullInt64
	UpdatedAt  string
}

type Playlist struct {
	ID          string
	UserID      string
	Name        string
	Description string
	ArtworkPath string
	CreatedAt   string
	UpdatedAt   string
}

type PlaylistItem struct {
	PlaylistID     string
	Position       int64
	Source         string
	TrackID        sql.NullString
	RefTitle       string
	RefAlbum       string
	RefAlbumArtist string
	RefDurationMs  int64
	AddedAt        string
}

type RecentAlbum struct {
	UserID       string
	AlbumName    string
	AlbumArtist  string
	FirstTrackID string
	PlayedAt     string
}

type RecentPlaylist struct {
	UserID     string
	PlaylistID string
	PlayedAt   string
}

type Track struct {
	ID               string
	Path             string
	Title            string
	AlbumArtist      sql.NullString
	AlbumName        sql.NullString
	Genre            sql.NullString
	Year             sql.NullInt64
	TrackNumber      sql.NullInt64
	DiscNumber       sql.NullInt64
	DurationMs       sql.NullInt64
	BitrateKbps      sql.NullInt64
	SampleRateHz     sql.NullInt64
	Codec            sql.NullString
	FileSizeBytes    sql.NullInt64
	LastModified     string
	Fingerprint      sql.NullString
	UploadedByUserID sql.NullString
	DeletedAt        sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

type User struct {
	ID           string
	Username     string
	PasswordHash string
	IsAdmin      int64
	CanUpload    int64
	CanEdit      int64
	CanDelete    int64
	CreatedAt    string
	UpdatedAt    string
}

type WatchFolder struct {
	ID        string
	Path      string
	UserID    string
	CreatedAt string
}
