// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package serverdb

import (
	"database/sql"
)

type Album struct {
	ID          string
	Title       string
	ArtistID    sql.NullString
	Year        sql.NullInt64
	MbReleaseID sql.NullString
	ArtworkID   sql.NullString
	CreatedAt   string
}

type Artist struct {
	ID         string
	Name       string
	MbArtistID sql.NullString
	CreatedAt  string
}

type Artwork struct {
	ID        string
	Path      string
	Width     sql.NullInt64
	Height    sql.NullInt64
	Format    sql.NullString
	CreatedAt string
}

type AuditLog struct {
	ID         string
	UserID     string
	Action     string
	TargetType string
	TargetID   string
	Detail     sql.NullString
	CreatedAt  string
}

type Device struct {
	ID         string
	UserID     string
	Name       string
	LastSeenAt sql.NullString
	CreatedAt  string
}

type OfflinePack struct {
	ID           string
	UserID       string
	TrackID      string
	LocalPath    string
	DownloadedAt string
}

type PlaybackSession struct {
	ID         string
	DeviceID   string
	UserID     string
	TrackID    sql.NullString
	PositionMs sql.NullInt64
	QueueJson  sql.NullString
	UpdatedAt  string
}

type Playlist struct {
	ID        string
	UserID    string
	Name      string
	CreatedAt string
	UpdatedAt string
}

type PlaylistTrack struct {
	PlaylistID string
	TrackID    string
	Position   int64
}

type Track struct {
	ID                  string
	Path                string
	Title               string
	ArtistID            sql.NullString
	AlbumID             sql.NullString
	AlbumArtist         sql.NullString
	AlbumName           sql.NullString
	Genre               sql.NullString
	Year                sql.NullInt64
	TrackNumber         sql.NullInt64
	DiscNumber          sql.NullInt64
	DurationMs          sql.NullInt64
	BitrateKbps         sql.NullInt64
	SampleRateHz        sql.NullInt64
	Codec               sql.NullString
	FileSizeBytes       sql.NullInt64
	LastModified        string
	Fingerprint         sql.NullString
	AcousticFingerprint string
	MbRecordingID       sql.NullString
	ReplayGainTrack     sql.NullFloat64
	ReplayGainAlbum     sql.NullFloat64
	ArtworkID           sql.NullString
	UploadedByUserID    sql.NullString
	DeletedAt           sql.NullString
	EnrichedAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

type User struct {
	ID           string
	Username     string
	PasswordHash string
	IsAdmin      int64
	CanUpload    int64
	CanEdit      int64
	CanDelete    int64
	CreatedAt    string
	UpdatedAt    string
}

type WatchFolder struct {
	ID        string
	Path      string
	UserID    string
	CreatedAt string
}
