// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playback.sql

package serverdb

import (
	"context"
	"database/sql"
)

const deleteOfflinePack = `-- name: DeleteOfflinePack :exec
DELETE FROM offline_packs WHERE user_id = ? AND track_id = ?
`

type DeleteOfflinePackParams struct {
	UserID  string
	TrackID string
}

func (q *Queries) DeleteOfflinePack(ctx context.Context, arg DeleteOfflinePackParams) error {
	_, err := q.db.ExecContext(ctx, deleteOfflinePack, arg.UserID, arg.TrackID)
	return err
}

const listOfflinePacks = `-- name: ListOfflinePacks :many
SELECT id, user_id, track_id, local_path, downloaded_at
FROM offline_packs WHERE user_id = ? ORDER BY downloaded_at DESC
`

func (q *Queries) ListOfflinePacks(ctx context.Context, userID string) ([]OfflinePack, error) {
	rows, err := q.db.QueryContext(ctx, listOfflinePacks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OfflinePack
	for rows.Next() {
		var i OfflinePack
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.LocalPath,
			&i.DownloadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playbackSessionByDevice = `-- name: PlaybackSessionByDevice :one
SELECT id, device_id, user_id, COALESCE(track_id,'') AS track_id, position_ms, queue_json, updated_at
FROM playback_sessions WHERE device_id = ? LIMIT 1
`

type PlaybackSessionByDeviceRow struct {
	ID         string
	DeviceID   string
	UserID     string
	TrackID    string
	PositionMs sql.NullInt64
	QueueJson  sql.NullString
	UpdatedAt  string
}

func (q *Queries) PlaybackSessionByDevice(ctx context.Context, deviceID string) (PlaybackSessionByDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, playbackSessionByDevice, deviceID)
	var i PlaybackSessionByDeviceRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.TrackID,
		&i.PositionMs,
		&i.QueueJson,
		&i.UpdatedAt,
	)
	return i, err
}

const playbackSessionsByUser = `-- name: PlaybackSessionsByUser :many
SELECT ps.id, ps.device_id, ps.user_id, COALESCE(ps.track_id,'') AS track_id,
       ps.position_ms, ps.queue_json, ps.updated_at
FROM playback_sessions ps
JOIN devices d ON d.id = ps.device_id
WHERE ps.user_id = ?
ORDER BY ps.updated_at DESC
`

type PlaybackSessionsByUserRow struct {
	ID         string
	DeviceID   string
	UserID     string
	TrackID    string
	PositionMs sql.NullInt64
	QueueJson  sql.NullString
	UpdatedAt  string
}

func (q *Queries) PlaybackSessionsByUser(ctx context.Context, userID string) ([]PlaybackSessionsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, playbackSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaybackSessionsByUserRow
	for rows.Next() {
		var i PlaybackSessionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.UserID,
			&i.TrackID,
			&i.PositionMs,
			&i.QueueJson,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOfflinePack = `-- name: UpsertOfflinePack :exec
INSERT INTO offline_packs (id, user_id, track_id, local_path, downloaded_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(user_id, track_id) DO UPDATE SET local_path=excluded.local_path, downloaded_at=excluded.downloaded_at
`

type UpsertOfflinePackParams struct {
	ID           string
	UserID       string
	TrackID      string
	LocalPath    string
	DownloadedAt string
}

func (q *Queries) UpsertOfflinePack(ctx context.Context, arg UpsertOfflinePackParams) error {
	_, err := q.db.ExecContext(ctx, upsertOfflinePack,
		arg.ID,
		arg.UserID,
		arg.TrackID,
		arg.LocalPath,
		arg.DownloadedAt,
	)
	return err
}

const upsertPlaybackSession = `-- name: UpsertPlaybackSession :exec
INSERT INTO playback_sessions (id, device_id, user_id, track_id, position_ms, queue_json, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(device_id) DO UPDATE SET
    track_id=excluded.track_id, position_ms=excluded.position_ms,
    queue_json=excluded.queue_json, updated_at=excluded.updated_at
`

type UpsertPlaybackSessionParams struct {
	ID         string
	DeviceID   string
	UserID     string
	TrackID    sql.NullString
	PositionMs sql.NullInt64
	QueueJson  sql.NullString
	UpdatedAt  string
}

func (q *Queries) UpsertPlaybackSession(ctx context.Context, arg UpsertPlaybackSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlaybackSession,
		arg.ID,
		arg.DeviceID,
		arg.UserID,
		arg.TrackID,
		arg.PositionMs,
		arg.QueueJson,
		arg.UpdatedAt,
	)
	return err
}
