// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlists.sql

package serverdb

import (
	"context"
	"database/sql"
)

const countPlaylistItems = `-- name: CountPlaylistItems :one
SELECT COUNT(*) FROM playlist_items WHERE playlist_id = ?
`

func (q *Queries) CountPlaylistItems(ctx context.Context, playlistID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaylistItems, playlistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlaylist = `-- name: CreatePlaylist :exec
INSERT INTO playlists (id, user_id, name, description, artwork_path, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreatePlaylistParams struct {
	ID          string
	UserID      string
	Name        string
	Description string
	ArtworkPath string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, createPlaylist,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.ArtworkPath,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists WHERE id = ?
`

func (q *Queries) DeletePlaylist(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlaylist, id)
	return err
}

const deletePlaylistItems = `-- name: DeletePlaylistItems :exec
DELETE FROM playlist_items WHERE playlist_id = ?
`

func (q *Queries) DeletePlaylistItems(ctx context.Context, playlistID string) error {
	_, err := q.db.ExecContext(ctx, deletePlaylistItems, playlistID)
	return err
}

const getPlaylistByID = `-- name: GetPlaylistByID :one
SELECT id, user_id, name, description, artwork_path, created_at, updated_at
FROM playlists WHERE id = ?
`

func (q *Queries) GetPlaylistByID(ctx context.Context, id string) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistByID, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ArtworkPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlaylistItem = `-- name: InsertPlaylistItem :exec
INSERT INTO playlist_items (playlist_id, position, source, track_id, ref_title, ref_album, ref_album_artist, ref_duration_ms, added_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPlaylistItemParams struct {
	PlaylistID     string
	Position       int64
	Source         string
	TrackID        sql.NullString
	RefTitle       string
	RefAlbum       string
	RefAlbumArtist string
	RefDurationMs  int64
	AddedAt        string
}

func (q *Queries) InsertPlaylistItem(ctx context.Context, arg InsertPlaylistItemParams) error {
	_, err := q.db.ExecContext(ctx, insertPlaylistItem,
		arg.PlaylistID,
		arg.Position,
		arg.Source,
		arg.TrackID,
		arg.RefTitle,
		arg.RefAlbum,
		arg.RefAlbumArtist,
		arg.RefDurationMs,
		arg.AddedAt,
	)
	return err
}

const listPlaylistItems = `-- name: ListPlaylistItems :many
SELECT pi.playlist_id, pi.position, pi.source,
       COALESCE(pi.track_id, '') AS track_id,
       pi.ref_title, pi.ref_album, pi.ref_album_artist, pi.ref_duration_ms, pi.added_at,
       CASE
           WHEN pi.source = 'remote' AND (pi.track_id IS NULL OR t.id IS NULL OR t.deleted_at IS NOT NULL)
           THEN 1 ELSE 0
       END AS missing
FROM playlist_items pi
LEFT JOIN tracks t ON t.id = pi.track_id
WHERE pi.playlist_id = ?
ORDER BY pi.position
`

type ListPlaylistItemsRow struct {
	PlaylistID     string
	Position       int64
	Source         string
	TrackID        string
	RefTitle       string
	RefAlbum       string
	RefAlbumArtist string
	RefDurationMs  int64
	AddedAt        string
	Missing        int64
}

func (q *Queries) ListPlaylistItems(ctx context.Context, playlistID string) ([]ListPlaylistItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistItems, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaylistItemsRow
	for rows.Next() {
		var i ListPlaylistItemsRow
		if err := rows.Scan(
			&i.PlaylistID,
			&i.Position,
			&i.Source,
			&i.TrackID,
			&i.RefTitle,
			&i.RefAlbum,
			&i.RefAlbumArtist,
			&i.RefDurationMs,
			&i.AddedAt,
			&i.Missing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsByUser = `-- name: ListPlaylistsByUser :many
SELECT p.id, p.user_id, p.name, p.description, p.artwork_path, p.created_at, p.updated_at,
       COUNT(pi.playlist_id) AS item_count,
       COALESCE(SUM(CASE
           WHEN pi.source = 'remote' THEN (SELECT COALESCE(t.duration_ms, 0) FROM tracks t WHERE t.id = pi.track_id)
           ELSE pi.ref_duration_ms
       END), 0) AS total_duration_ms
FROM playlists p
LEFT JOIN playlist_items pi ON pi.playlist_id = p.id
WHERE p.user_id = ?
GROUP BY p.id
ORDER BY p.updated_at DESC
`

type ListPlaylistsByUserRow struct {
	ID              string
	UserID          string
	Name            string
	Description     string
	ArtworkPath     string
	CreatedAt       string
	UpdatedAt       string
	ItemCount       int64
	TotalDurationMs interface{}
}

func (q *Queries) ListPlaylistsByUser(ctx context.Context, userID string) ([]ListPlaylistsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaylistsByUserRow
	for rows.Next() {
		var i ListPlaylistsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ArtworkPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemCount,
			&i.TotalDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchPlaylist = `-- name: TouchPlaylist :exec
UPDATE playlists SET updated_at = ? WHERE id = ?
`

type TouchPlaylistParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) TouchPlaylist(ctx context.Context, arg TouchPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, touchPlaylist, arg.UpdatedAt, arg.ID)
	return err
}

const updatePlaylist = `-- name: UpdatePlaylist :exec
UPDATE playlists SET name = ?, description = ?, artwork_path = ?, updated_at = ?
WHERE id = ?
`

type UpdatePlaylistParams struct {
	Name        string
	Description string
	ArtworkPath string
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, updatePlaylist,
		arg.Name,
		arg.Description,
		arg.ArtworkPath,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
