// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recently_played.sql

package serverdb

import (
	"context"
)

const clearRecentAlbumsByUser = `-- name: ClearRecentAlbumsByUser :exec
DELETE FROM recent_albums WHERE user_id = ?
`

func (q *Queries) ClearRecentAlbumsByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, clearRecentAlbumsByUser, userID)
	return err
}

const clearRecentPlaylistsByUser = `-- name: ClearRecentPlaylistsByUser :exec
DELETE FROM recent_playlists WHERE user_id = ?
`

func (q *Queries) ClearRecentPlaylistsByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, clearRecentPlaylistsByUser, userID)
	return err
}

const deleteRecentPlaylist = `-- name: DeleteRecentPlaylist :exec
DELETE FROM recent_playlists
WHERE user_id = ? AND playlist_id = ?
`

type DeleteRecentPlaylistParams struct {
	UserID     string
	PlaylistID string
}

func (q *Queries) DeleteRecentPlaylist(ctx context.Context, arg DeleteRecentPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, deleteRecentPlaylist, arg.UserID, arg.PlaylistID)
	return err
}

const listRecentAlbumsByUser = `-- name: ListRecentAlbumsByUser :many
SELECT album_name, album_artist, first_track_id, played_at
FROM recent_albums
WHERE user_id = ?
ORDER BY played_at DESC
LIMIT 50
`

type ListRecentAlbumsByUserRow struct {
	AlbumName    string
	AlbumArtist  string
	FirstTrackID string
	PlayedAt     string
}

func (q *Queries) ListRecentAlbumsByUser(ctx context.Context, userID string) ([]ListRecentAlbumsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentAlbumsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentAlbumsByUserRow
	for rows.Next() {
		var i ListRecentAlbumsByUserRow
		if err := rows.Scan(
			&i.AlbumName,
			&i.AlbumArtist,
			&i.FirstTrackID,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPlaylistsByUser = `-- name: ListRecentPlaylistsByUser :many
SELECT rp.playlist_id, p.name, COALESCE(p.artwork_path, '') AS artwork_path, rp.played_at
FROM recent_playlists rp
JOIN playlists p ON p.id = rp.playlist_id
WHERE rp.user_id = ?
ORDER BY rp.played_at DESC
LIMIT 50
`

type ListRecentPlaylistsByUserRow struct {
	PlaylistID  string
	Name        string
	ArtworkPath string
	PlayedAt    string
}

func (q *Queries) ListRecentPlaylistsByUser(ctx context.Context, userID string) ([]ListRecentPlaylistsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPlaylistsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentPlaylistsByUserRow
	for rows.Next() {
		var i ListRecentPlaylistsByUserRow
		if err := rows.Scan(
			&i.PlaylistID,
			&i.Name,
			&i.ArtworkPath,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRecentAlbum = `-- name: UpsertRecentAlbum :exec
INSERT INTO recent_albums (user_id, album_name, album_artist, first_track_id, played_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (user_id, album_name, album_artist) DO UPDATE SET
    first_track_id = excluded.first_track_id,
    played_at = excluded.played_at
`

type UpsertRecentAlbumParams struct {
	UserID       string
	AlbumName    string
	AlbumArtist  string
	FirstTrackID string
	PlayedAt     string
}

func (q *Queries) UpsertRecentAlbum(ctx context.Context, arg UpsertRecentAlbumParams) error {
	_, err := q.db.ExecContext(ctx, upsertRecentAlbum,
		arg.UserID,
		arg.AlbumName,
		arg.AlbumArtist,
		arg.FirstTrackID,
		arg.PlayedAt,
	)
	return err
}

const upsertRecentPlaylist = `-- name: UpsertRecentPlaylist :exec
INSERT INTO recent_playlists (user_id, playlist_id, played_at)
VALUES (?, ?, ?)
ON CONFLICT (user_id, playlist_id) DO UPDATE SET
    played_at = excluded.played_at
`

type UpsertRecentPlaylistParams struct {
	UserID     string
	PlaylistID string
	PlayedAt   string
}

func (q *Queries) UpsertRecentPlaylist(ctx context.Context, arg UpsertRecentPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, upsertRecentPlaylist, arg.UserID, arg.PlaylistID, arg.PlayedAt)
	return err
}
