// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telemetry.sql

package serverdb

import (
	"context"
	"database/sql"
)

const clearStreamTelemetry = `-- name: ClearStreamTelemetry :exec
DELETE FROM stream_telemetry
`

func (q *Queries) ClearStreamTelemetry(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearStreamTelemetry)
	return err
}

const getStreamTelemetryStats = `-- name: GetStreamTelemetryStats :many
SELECT
    st.track_id,
    t.title AS track_title,
    t.album_artist AS track_artist,
    t.codec AS track_codec,
    t.file_size_bytes AS track_file_size,
    t.duration_ms AS track_duration_ms,
    st.stream_quality,
    COUNT(*) AS sample_count,
    CAST(AVG(st.latency_ms) AS INTEGER) AS avg_latency_ms,
    MIN(st.latency_ms) AS min_latency_ms,
    MAX(st.latency_ms) AS max_latency_ms,
    CAST(SUM(st.stutter_count) AS INTEGER) AS total_stutters,
    CAST(AVG(st.stutter_duration_ms) AS INTEGER) AS avg_stutter_duration_ms
FROM stream_telemetry st
LEFT JOIN tracks t ON t.id = st.track_id AND t.deleted_at IS NULL
GROUP BY st.track_id, st.stream_quality
ORDER BY avg_latency_ms DESC
`

type GetStreamTelemetryStatsRow struct {
	TrackID              string
	TrackTitle           sql.NullString
	TrackArtist          sql.NullString
	TrackCodec           sql.NullString
	TrackFileSize        sql.NullInt64
	TrackDurationMs      sql.NullInt64
	StreamQuality        string
	SampleCount          int64
	AvgLatencyMs         int64
	MinLatencyMs         interface{}
	MaxLatencyMs         interface{}
	TotalStutters        int64
	AvgStutterDurationMs int64
}

func (q *Queries) GetStreamTelemetryStats(ctx context.Context) ([]GetStreamTelemetryStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStreamTelemetryStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStreamTelemetryStatsRow
	for rows.Next() {
		var i GetStreamTelemetryStatsRow
		if err := rows.Scan(
			&i.TrackID,
			&i.TrackTitle,
			&i.TrackArtist,
			&i.TrackCodec,
			&i.TrackFileSize,
			&i.TrackDurationMs,
			&i.StreamQuality,
			&i.SampleCount,
			&i.AvgLatencyMs,
			&i.MinLatencyMs,
			&i.MaxLatencyMs,
			&i.TotalStutters,
			&i.AvgStutterDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertStreamTelemetry = `-- name: InsertStreamTelemetry :exec
INSERT INTO stream_telemetry (
    id, track_id, user_id, device_id, stream_quality,
    latency_ms, stutter_count, stutter_duration_ms, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertStreamTelemetryParams struct {
	ID                string
	TrackID           string
	UserID            string
	DeviceID          string
	StreamQuality     string
	LatencyMs         int64
	StutterCount      int64
	StutterDurationMs int64
	CreatedAt         string
}

func (q *Queries) InsertStreamTelemetry(ctx context.Context, arg InsertStreamTelemetryParams) error {
	_, err := q.db.ExecContext(ctx, insertStreamTelemetry,
		arg.ID,
		arg.TrackID,
		arg.UserID,
		arg.DeviceID,
		arg.StreamQuality,
		arg.LatencyMs,
		arg.StutterCount,
		arg.StutterDurationMs,
		arg.CreatedAt,
	)
	return err
}
