// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracks.sql

package serverdb

import (
	"context"
	"database/sql"
)

const countTracks = `-- name: CountTracks :one
SELECT COUNT(*) FROM tracks WHERE tracks.deleted_at IS NULL
`

func (q *Queries) CountTracks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTracks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDuplicateFingerprints = `-- name: DeleteDuplicateFingerprints :execresult
DELETE FROM tracks
WHERE fingerprint != '' AND fingerprint IS NOT NULL
AND rowid NOT IN (
    SELECT MIN(rowid) FROM tracks
    WHERE fingerprint != '' AND fingerprint IS NOT NULL
    GROUP BY fingerprint
)
`

func (q *Queries) DeleteDuplicateFingerprints(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteDuplicateFingerprints)
}

const deleteTrackByPath = `-- name: DeleteTrackByPath :exec
DELETE FROM tracks WHERE tracks.path = ?
`

func (q *Queries) DeleteTrackByPath(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteTrackByPath, path)
	return err
}

const listTracks = `-- name: ListTracks :many
SELECT id, path, title, COALESCE(artist_id,'') AS artist_id, COALESCE(album_id,'') AS album_id,
    CAST(COALESCE((SELECT name FROM artists WHERE artists.id=tracks.artist_id),'') AS TEXT) AS artist_name,
    album_artist, album_name, genre, year,
    track_number, disc_number, duration_ms, bitrate_kbps, sample_rate_hz,
    codec, file_size_bytes, last_modified, fingerprint, acoustic_fingerprint, mb_recording_id,
    replay_gain_track, replay_gain_album, COALESCE(artwork_id,'') AS artwork_id,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id, deleted_at,
    enriched_at, created_at, updated_at
FROM tracks WHERE tracks.deleted_at IS NULL ORDER BY title COLLATE NOCASE
`

type ListTracksRow struct {
	ID                  string
	Path                string
	Title               string
	ArtistID            string
	AlbumID             string
	ArtistName          string
	AlbumArtist         sql.NullString
	AlbumName           sql.NullString
	Genre               sql.NullString
	Year                sql.NullInt64
	TrackNumber         sql.NullInt64
	DiscNumber          sql.NullInt64
	DurationMs          sql.NullInt64
	BitrateKbps         sql.NullInt64
	SampleRateHz        sql.NullInt64
	Codec               sql.NullString
	FileSizeBytes       sql.NullInt64
	LastModified        string
	Fingerprint         sql.NullString
	AcousticFingerprint string
	MbRecordingID       sql.NullString
	ReplayGainTrack     sql.NullFloat64
	ReplayGainAlbum     sql.NullFloat64
	ArtworkID           string
	UploadedByUserID    string
	DeletedAt           sql.NullString
	EnrichedAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) ListTracks(ctx context.Context) ([]ListTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksRow
	for rows.Next() {
		var i ListTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.ArtistID,
			&i.AlbumID,
			&i.ArtistName,
			&i.AlbumArtist,
			&i.AlbumName,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.SampleRateHz,
			&i.Codec,
			&i.FileSizeBytes,
			&i.LastModified,
			&i.Fingerprint,
			&i.AcousticFingerprint,
			&i.MbRecordingID,
			&i.ReplayGainTrack,
			&i.ReplayGainAlbum,
			&i.ArtworkID,
			&i.UploadedByUserID,
			&i.DeletedAt,
			&i.EnrichedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByAlbumName = `-- name: ListTracksByAlbumName :many
SELECT id, path, title, COALESCE(artist_id,'') AS artist_id, COALESCE(album_id,'') AS album_id,
    CAST(COALESCE((SELECT name FROM artists WHERE artists.id=tracks.artist_id),'') AS TEXT) AS artist_name,
    album_artist, album_name, genre, year,
    track_number, disc_number, duration_ms, bitrate_kbps, sample_rate_hz,
    codec, file_size_bytes, last_modified, fingerprint, acoustic_fingerprint, mb_recording_id,
    replay_gain_track, replay_gain_album, COALESCE(artwork_id,'') AS artwork_id,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id, deleted_at,
    enriched_at, created_at, updated_at
FROM tracks WHERE tracks.deleted_at IS NULL AND album_name = ?
ORDER BY disc_number, track_number, title COLLATE NOCASE
`

type ListTracksByAlbumNameRow struct {
	ID                  string
	Path                string
	Title               string
	ArtistID            string
	AlbumID             string
	ArtistName          string
	AlbumArtist         sql.NullString
	AlbumName           sql.NullString
	Genre               sql.NullString
	Year                sql.NullInt64
	TrackNumber         sql.NullInt64
	DiscNumber          sql.NullInt64
	DurationMs          sql.NullInt64
	BitrateKbps         sql.NullInt64
	SampleRateHz        sql.NullInt64
	Codec               sql.NullString
	FileSizeBytes       sql.NullInt64
	LastModified        string
	Fingerprint         sql.NullString
	AcousticFingerprint string
	MbRecordingID       sql.NullString
	ReplayGainTrack     sql.NullFloat64
	ReplayGainAlbum     sql.NullFloat64
	ArtworkID           string
	UploadedByUserID    string
	DeletedAt           sql.NullString
	EnrichedAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) ListTracksByAlbumName(ctx context.Context, albumName sql.NullString) ([]ListTracksByAlbumNameRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracksByAlbumName, albumName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksByAlbumNameRow
	for rows.Next() {
		var i ListTracksByAlbumNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.ArtistID,
			&i.AlbumID,
			&i.ArtistName,
			&i.AlbumArtist,
			&i.AlbumName,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.SampleRateHz,
			&i.Codec,
			&i.FileSizeBytes,
			&i.LastModified,
			&i.Fingerprint,
			&i.AcousticFingerprint,
			&i.MbRecordingID,
			&i.ReplayGainTrack,
			&i.ReplayGainAlbum,
			&i.ArtworkID,
			&i.UploadedByUserID,
			&i.DeletedAt,
			&i.EnrichedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByAlbumNameAndArtist = `-- name: ListTracksByAlbumNameAndArtist :many
SELECT id, path, title, COALESCE(artist_id,'') AS artist_id, COALESCE(album_id,'') AS album_id,
    CAST(COALESCE((SELECT name FROM artists WHERE artists.id=tracks.artist_id),'') AS TEXT) AS artist_name,
    album_artist, album_name, genre, year,
    track_number, disc_number, duration_ms, bitrate_kbps, sample_rate_hz,
    codec, file_size_bytes, last_modified, fingerprint, acoustic_fingerprint, mb_recording_id,
    replay_gain_track, replay_gain_album, COALESCE(artwork_id,'') AS artwork_id,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id, deleted_at,
    enriched_at, created_at, updated_at
FROM tracks WHERE tracks.deleted_at IS NULL AND album_name = ? AND COALESCE(album_artist,'') = ?
ORDER BY disc_number, track_number, title COLLATE NOCASE
`

type ListTracksByAlbumNameAndArtistParams struct {
	AlbumName   sql.NullString
	AlbumArtist sql.NullString
}

type ListTracksByAlbumNameAndArtistRow struct {
	ID                  string
	Path                string
	Title               string
	ArtistID            string
	AlbumID             string
	ArtistName          string
	AlbumArtist         sql.NullString
	AlbumName           sql.NullString
	Genre               sql.NullString
	Year                sql.NullInt64
	TrackNumber         sql.NullInt64
	DiscNumber          sql.NullInt64
	DurationMs          sql.NullInt64
	BitrateKbps         sql.NullInt64
	SampleRateHz        sql.NullInt64
	Codec               sql.NullString
	FileSizeBytes       sql.NullInt64
	LastModified        string
	Fingerprint         sql.NullString
	AcousticFingerprint string
	MbRecordingID       sql.NullString
	ReplayGainTrack     sql.NullFloat64
	ReplayGainAlbum     sql.NullFloat64
	ArtworkID           string
	UploadedByUserID    string
	DeletedAt           sql.NullString
	EnrichedAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) ListTracksByAlbumNameAndArtist(ctx context.Context, arg ListTracksByAlbumNameAndArtistParams) ([]ListTracksByAlbumNameAndArtistRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracksByAlbumNameAndArtist, arg.AlbumName, arg.AlbumArtist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksByAlbumNameAndArtistRow
	for rows.Next() {
		var i ListTracksByAlbumNameAndArtistRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.ArtistID,
			&i.AlbumID,
			&i.ArtistName,
			&i.AlbumArtist,
			&i.AlbumName,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.SampleRateHz,
			&i.Codec,
			&i.FileSizeBytes,
			&i.LastModified,
			&i.Fingerprint,
			&i.AcousticFingerprint,
			&i.MbRecordingID,
			&i.ReplayGainTrack,
			&i.ReplayGainAlbum,
			&i.ArtworkID,
			&i.UploadedByUserID,
			&i.DeletedAt,
			&i.EnrichedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByAlbumUnorganized = `-- name: ListTracksByAlbumUnorganized :many
SELECT id, path, title, COALESCE(artist_id,'') AS artist_id, COALESCE(album_id,'') AS album_id,
    CAST(COALESCE((SELECT name FROM artists WHERE artists.id=tracks.artist_id),'') AS TEXT) AS artist_name,
    album_artist, album_name, genre, year,
    track_number, disc_number, duration_ms, bitrate_kbps, sample_rate_hz,
    codec, file_size_bytes, last_modified, fingerprint, acoustic_fingerprint, mb_recording_id,
    replay_gain_track, replay_gain_album, COALESCE(artwork_id,'') AS artwork_id,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id, deleted_at,
    enriched_at, created_at, updated_at
FROM tracks WHERE tracks.deleted_at IS NULL AND TRIM(COALESCE(album_name,''))=''
ORDER BY disc_number, track_number, title COLLATE NOCASE
`

type ListTracksByAlbumUnorganizedRow struct {
	ID                  string
	Path                string
	Title               string
	ArtistID            string
	AlbumID             string
	ArtistName          string
	AlbumArtist         sql.NullString
	AlbumName           sql.NullString
	Genre               sql.NullString
	Year                sql.NullInt64
	TrackNumber         sql.NullInt64
	DiscNumber          sql.NullInt64
	DurationMs          sql.NullInt64
	BitrateKbps         sql.NullInt64
	SampleRateHz        sql.NullInt64
	Codec               sql.NullString
	FileSizeBytes       sql.NullInt64
	LastModified        string
	Fingerprint         sql.NullString
	AcousticFingerprint string
	MbRecordingID       sql.NullString
	ReplayGainTrack     sql.NullFloat64
	ReplayGainAlbum     sql.NullFloat64
	ArtworkID           string
	UploadedByUserID    string
	DeletedAt           sql.NullString
	EnrichedAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) ListTracksByAlbumUnorganized(ctx context.Context) ([]ListTracksByAlbumUnorganizedRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracksByAlbumUnorganized)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksByAlbumUnorganizedRow
	for rows.Next() {
		var i ListTracksByAlbumUnorganizedRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.ArtistID,
			&i.AlbumID,
			&i.ArtistName,
			&i.AlbumArtist,
			&i.AlbumName,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.SampleRateHz,
			&i.Codec,
			&i.FileSizeBytes,
			&i.LastModified,
			&i.Fingerprint,
			&i.AcousticFingerprint,
			&i.MbRecordingID,
			&i.ReplayGainTrack,
			&i.ReplayGainAlbum,
			&i.ArtworkID,
			&i.UploadedByUserID,
			&i.DeletedAt,
			&i.EnrichedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksPage = `-- name: ListTracksPage :many
SELECT id, path, title, COALESCE(artist_id,'') AS artist_id, COALESCE(album_id,'') AS album_id,
    CAST(COALESCE((SELECT name FROM artists WHERE artists.id=tracks.artist_id),'') AS TEXT) AS artist_name,
    album_artist, album_name, genre, year,
    track_number, disc_number, duration_ms, bitrate_kbps, sample_rate_hz,
    codec, file_size_bytes, last_modified, fingerprint, acoustic_fingerprint, mb_recording_id,
    replay_gain_track, replay_gain_album, COALESCE(artwork_id,'') AS artwork_id,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id, deleted_at,
    enriched_at, created_at, updated_at
FROM tracks WHERE tracks.deleted_at IS NULL ORDER BY title COLLATE NOCASE LIMIT ? OFFSET ?
`

type ListTracksPageParams struct {
	Limit  int64
	Offset int64
}

type ListTracksPageRow struct {
	ID                  string
	Path                string
	Title               string
	ArtistID            string
	AlbumID             string
	ArtistName          string
	AlbumArtist         sql.NullString
	AlbumName           sql.NullString
	Genre               sql.NullString
	Year                sql.NullInt64
	TrackNumber         sql.NullInt64
	DiscNumber          sql.NullInt64
	DurationMs          sql.NullInt64
	BitrateKbps         sql.NullInt64
	SampleRateHz        sql.NullInt64
	Codec               sql.NullString
	FileSizeBytes       sql.NullInt64
	LastModified        string
	Fingerprint         sql.NullString
	AcousticFingerprint string
	MbRecordingID       sql.NullString
	ReplayGainTrack     sql.NullFloat64
	ReplayGainAlbum     sql.NullFloat64
	ArtworkID           string
	UploadedByUserID    string
	DeletedAt           sql.NullString
	EnrichedAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) ListTracksPage(ctx context.Context, arg ListTracksPageParams) ([]ListTracksPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracksPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksPageRow
	for rows.Next() {
		var i ListTracksPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.ArtistID,
			&i.AlbumID,
			&i.ArtistName,
			&i.AlbumArtist,
			&i.AlbumName,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.SampleRateHz,
			&i.Codec,
			&i.FileSizeBytes,
			&i.LastModified,
			&i.Fingerprint,
			&i.AcousticFingerprint,
			&i.MbRecordingID,
			&i.ReplayGainTrack,
			&i.ReplayGainAlbum,
			&i.ArtworkID,
			&i.UploadedByUserID,
			&i.DeletedAt,
			&i.EnrichedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreTrack = `-- name: RestoreTrack :exec
UPDATE tracks SET deleted_at = NULL, updated_at = ? WHERE id = ?
`

type RestoreTrackParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) RestoreTrack(ctx context.Context, arg RestoreTrackParams) error {
	_, err := q.db.ExecContext(ctx, restoreTrack, arg.UpdatedAt, arg.ID)
	return err
}

const searchTracks = `-- name: SearchTracks :many
SELECT id, path, title, COALESCE(artist_id,'') AS artist_id, COALESCE(album_id,'') AS album_id,
    CAST(COALESCE((SELECT name FROM artists WHERE artists.id=tracks.artist_id),'') AS TEXT) AS artist_name,
    album_artist, album_name, genre, year,
    track_number, disc_number, duration_ms, bitrate_kbps, sample_rate_hz,
    codec, file_size_bytes, last_modified, fingerprint, acoustic_fingerprint, mb_recording_id,
    replay_gain_track, replay_gain_album, COALESCE(artwork_id,'') AS artwork_id,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id, deleted_at,
    enriched_at, created_at, updated_at
FROM tracks
WHERE tracks.deleted_at IS NULL
  AND (title LIKE ?1
    OR album_name LIKE ?1
    OR album_artist LIKE ?1
    OR COALESCE((SELECT name FROM artists WHERE artists.id=tracks.artist_id),'') LIKE ?1
    OR genre LIKE ?1)
ORDER BY title COLLATE NOCASE LIMIT 200
`

type SearchTracksRow struct {
	ID                  string
	Path                string
	Title               string
	ArtistID            string
	AlbumID             string
	ArtistName          string
	AlbumArtist         sql.NullString
	AlbumName           sql.NullString
	Genre               sql.NullString
	Year                sql.NullInt64
	TrackNumber         sql.NullInt64
	DiscNumber          sql.NullInt64
	DurationMs          sql.NullInt64
	BitrateKbps         sql.NullInt64
	SampleRateHz        sql.NullInt64
	Codec               sql.NullString
	FileSizeBytes       sql.NullInt64
	LastModified        string
	Fingerprint         sql.NullString
	AcousticFingerprint string
	MbRecordingID       sql.NullString
	ReplayGainTrack     sql.NullFloat64
	ReplayGainAlbum     sql.NullFloat64
	ArtworkID           string
	UploadedByUserID    string
	DeletedAt           sql.NullString
	EnrichedAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) SearchTracks(ctx context.Context, pattern string) ([]SearchTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTracks, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTracksRow
	for rows.Next() {
		var i SearchTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.ArtistID,
			&i.AlbumID,
			&i.ArtistName,
			&i.AlbumArtist,
			&i.AlbumName,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.SampleRateHz,
			&i.Codec,
			&i.FileSizeBytes,
			&i.LastModified,
			&i.Fingerprint,
			&i.AcousticFingerprint,
			&i.MbRecordingID,
			&i.ReplayGainTrack,
			&i.ReplayGainAlbum,
			&i.ArtworkID,
			&i.UploadedByUserID,
			&i.DeletedAt,
			&i.EnrichedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTrack = `-- name: SoftDeleteTrack :exec
UPDATE tracks SET deleted_at = ?, updated_at = ? WHERE id = ?
`

type SoftDeleteTrackParams struct {
	DeletedAt sql.NullString
	UpdatedAt string
	ID        string
}

func (q *Queries) SoftDeleteTrack(ctx context.Context, arg SoftDeleteTrackParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteTrack, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const trackByAcousticFingerprint = `-- name: TrackByAcousticFingerprint :one
SELECT id, path, title, COALESCE(artist_id,'') AS artist_id, COALESCE(album_id,'') AS album_id,
    CAST(COALESCE((SELECT name FROM artists WHERE artists.id=tracks.artist_id),'') AS TEXT) AS artist_name,
    album_artist, album_name, genre, year,
    track_number, disc_number, duration_ms, bitrate_kbps, sample_rate_hz,
    codec, file_size_bytes, last_modified, fingerprint, acoustic_fingerprint, mb_recording_id,
    replay_gain_track, replay_gain_album, COALESCE(artwork_id,'') AS artwork_id,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id, deleted_at,
    enriched_at, created_at, updated_at
FROM tracks WHERE tracks.acoustic_fingerprint = ? AND acoustic_fingerprint != '' AND deleted_at IS NULL LIMIT 1
`

type TrackByAcousticFingerprintRow struct {
	ID                  string
	Path                string
	Title               string
	ArtistID            string
	AlbumID             string
	ArtistName          string
	AlbumArtist         sql.NullString
	AlbumName           sql.NullString
	Genre               sql.NullString
	Year                sql.NullInt64
	TrackNumber         sql.NullInt64
	DiscNumber          sql.NullInt64
	DurationMs          sql.NullInt64
	BitrateKbps         sql.NullInt64
	SampleRateHz        sql.NullInt64
	Codec               sql.NullString
	FileSizeBytes       sql.NullInt64
	LastModified        string
	Fingerprint         sql.NullString
	AcousticFingerprint string
	MbRecordingID       sql.NullString
	ReplayGainTrack     sql.NullFloat64
	ReplayGainAlbum     sql.NullFloat64
	ArtworkID           string
	UploadedByUserID    string
	DeletedAt           sql.NullString
	EnrichedAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) TrackByAcousticFingerprint(ctx context.Context, acousticFingerprint string) (TrackByAcousticFingerprintRow, error) {
	row := q.db.QueryRowContext(ctx, trackByAcousticFingerprint, acousticFingerprint)
	var i TrackByAcousticFingerprintRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Title,
		&i.ArtistID,
		&i.AlbumID,
		&i.ArtistName,
		&i.AlbumArtist,
		&i.AlbumName,
		&i.Genre,
		&i.Year,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.SampleRateHz,
		&i.Codec,
		&i.FileSizeBytes,
		&i.LastModified,
		&i.Fingerprint,
		&i.AcousticFingerprint,
		&i.MbRecordingID,
		&i.ReplayGainTrack,
		&i.ReplayGainAlbum,
		&i.ArtworkID,
		&i.UploadedByUserID,
		&i.DeletedAt,
		&i.EnrichedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trackByFingerprint = `-- name: TrackByFingerprint :one
SELECT id, path, title, COALESCE(artist_id,'') AS artist_id, COALESCE(album_id,'') AS album_id,
    CAST(COALESCE((SELECT name FROM artists WHERE artists.id=tracks.artist_id),'') AS TEXT) AS artist_name,
    album_artist, album_name, genre, year,
    track_number, disc_number, duration_ms, bitrate_kbps, sample_rate_hz,
    codec, file_size_bytes, last_modified, fingerprint, acoustic_fingerprint, mb_recording_id,
    replay_gain_track, replay_gain_album, COALESCE(artwork_id,'') AS artwork_id,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id, deleted_at,
    enriched_at, created_at, updated_at
FROM tracks WHERE tracks.fingerprint = ? AND fingerprint != '' LIMIT 1
`

type TrackByFingerprintRow struct {
	ID                  string
	Path                string
	Title               string
	ArtistID            string
	AlbumID             string
	ArtistName          string
	AlbumArtist         sql.NullString
	AlbumName           sql.NullString
	Genre               sql.NullString
	Year                sql.NullInt64
	TrackNumber         sql.NullInt64
	DiscNumber          sql.NullInt64
	DurationMs          sql.NullInt64
	BitrateKbps         sql.NullInt64
	SampleRateHz        sql.NullInt64
	Codec               sql.NullString
	FileSizeBytes       sql.NullInt64
	LastModified        string
	Fingerprint         sql.NullString
	AcousticFingerprint string
	MbRecordingID       sql.NullString
	ReplayGainTrack     sql.NullFloat64
	ReplayGainAlbum     sql.NullFloat64
	ArtworkID           string
	UploadedByUserID    string
	DeletedAt           sql.NullString
	EnrichedAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) TrackByFingerprint(ctx context.Context, fingerprint sql.NullString) (TrackByFingerprintRow, error) {
	row := q.db.QueryRowContext(ctx, trackByFingerprint, fingerprint)
	var i TrackByFingerprintRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Title,
		&i.ArtistID,
		&i.AlbumID,
		&i.ArtistName,
		&i.AlbumArtist,
		&i.AlbumName,
		&i.Genre,
		&i.Year,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.SampleRateHz,
		&i.Codec,
		&i.FileSizeBytes,
		&i.LastModified,
		&i.Fingerprint,
		&i.AcousticFingerprint,
		&i.MbRecordingID,
		&i.ReplayGainTrack,
		&i.ReplayGainAlbum,
		&i.ArtworkID,
		&i.UploadedByUserID,
		&i.DeletedAt,
		&i.EnrichedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trackByID = `-- name: TrackByID :one
SELECT id, path, title, COALESCE(artist_id,'') AS artist_id, COALESCE(album_id,'') AS album_id,
    CAST(COALESCE((SELECT name FROM artists WHERE artists.id=tracks.artist_id),'') AS TEXT) AS artist_name,
    album_artist, album_name, genre, year,
    track_number, disc_number, duration_ms, bitrate_kbps, sample_rate_hz,
    codec, file_size_bytes, last_modified, fingerprint, acoustic_fingerprint, mb_recording_id,
    replay_gain_track, replay_gain_album, COALESCE(artwork_id,'') AS artwork_id,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id, deleted_at,
    enriched_at, created_at, updated_at
FROM tracks WHERE tracks.id = ? LIMIT 1
`

type TrackByIDRow struct {
	ID                  string
	Path                string
	Title               string
	ArtistID            string
	AlbumID             string
	ArtistName          string
	AlbumArtist         sql.NullString
	AlbumName           sql.NullString
	Genre               sql.NullString
	Year                sql.NullInt64
	TrackNumber         sql.NullInt64
	DiscNumber          sql.NullInt64
	DurationMs          sql.NullInt64
	BitrateKbps         sql.NullInt64
	SampleRateHz        sql.NullInt64
	Codec               sql.NullString
	FileSizeBytes       sql.NullInt64
	LastModified        string
	Fingerprint         sql.NullString
	AcousticFingerprint string
	MbRecordingID       sql.NullString
	ReplayGainTrack     sql.NullFloat64
	ReplayGainAlbum     sql.NullFloat64
	ArtworkID           string
	UploadedByUserID    string
	DeletedAt           sql.NullString
	EnrichedAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) TrackByID(ctx context.Context, id string) (TrackByIDRow, error) {
	row := q.db.QueryRowContext(ctx, trackByID, id)
	var i TrackByIDRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Title,
		&i.ArtistID,
		&i.AlbumID,
		&i.ArtistName,
		&i.AlbumArtist,
		&i.AlbumName,
		&i.Genre,
		&i.Year,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.SampleRateHz,
		&i.Codec,
		&i.FileSizeBytes,
		&i.LastModified,
		&i.Fingerprint,
		&i.AcousticFingerprint,
		&i.MbRecordingID,
		&i.ReplayGainTrack,
		&i.ReplayGainAlbum,
		&i.ArtworkID,
		&i.UploadedByUserID,
		&i.DeletedAt,
		&i.EnrichedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trackByPath = `-- name: TrackByPath :one
SELECT id, path, title, COALESCE(artist_id,'') AS artist_id, COALESCE(album_id,'') AS album_id,
    CAST(COALESCE((SELECT name FROM artists WHERE artists.id=tracks.artist_id),'') AS TEXT) AS artist_name,
    album_artist, album_name, genre, year,
    track_number, disc_number, duration_ms, bitrate_kbps, sample_rate_hz,
    codec, file_size_bytes, last_modified, fingerprint, acoustic_fingerprint, mb_recording_id,
    replay_gain_track, replay_gain_album, COALESCE(artwork_id,'') AS artwork_id,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id, deleted_at,
    enriched_at, created_at, updated_at
FROM tracks WHERE tracks.path = ? LIMIT 1
`

type TrackByPathRow struct {
	ID                  string
	Path                string
	Title               string
	ArtistID            string
	AlbumID             string
	ArtistName          string
	AlbumArtist         sql.NullString
	AlbumName           sql.NullString
	Genre               sql.NullString
	Year                sql.NullInt64
	TrackNumber         sql.NullInt64
	DiscNumber          sql.NullInt64
	DurationMs          sql.NullInt64
	BitrateKbps         sql.NullInt64
	SampleRateHz        sql.NullInt64
	Codec               sql.NullString
	FileSizeBytes       sql.NullInt64
	LastModified        string
	Fingerprint         sql.NullString
	AcousticFingerprint string
	MbRecordingID       sql.NullString
	ReplayGainTrack     sql.NullFloat64
	ReplayGainAlbum     sql.NullFloat64
	ArtworkID           string
	UploadedByUserID    string
	DeletedAt           sql.NullString
	EnrichedAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) TrackByPath(ctx context.Context, path string) (TrackByPathRow, error) {
	row := q.db.QueryRowContext(ctx, trackByPath, path)
	var i TrackByPathRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Title,
		&i.ArtistID,
		&i.AlbumID,
		&i.ArtistName,
		&i.AlbumArtist,
		&i.AlbumName,
		&i.Genre,
		&i.Year,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.SampleRateHz,
		&i.Codec,
		&i.FileSizeBytes,
		&i.LastModified,
		&i.Fingerprint,
		&i.AcousticFingerprint,
		&i.MbRecordingID,
		&i.ReplayGainTrack,
		&i.ReplayGainAlbum,
		&i.ArtworkID,
		&i.UploadedByUserID,
		&i.DeletedAt,
		&i.EnrichedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trackDuplicateByMeta = `-- name: TrackDuplicateByMeta :one
SELECT id, path, title, COALESCE(artist_id,'') AS artist_id, COALESCE(album_id,'') AS album_id,
    CAST(COALESCE((SELECT name FROM artists WHERE artists.id=tracks.artist_id),'') AS TEXT) AS artist_name,
    album_artist, album_name, genre, year,
    track_number, disc_number, duration_ms, bitrate_kbps, sample_rate_hz,
    codec, file_size_bytes, last_modified, fingerprint, acoustic_fingerprint, mb_recording_id,
    replay_gain_track, replay_gain_album, COALESCE(artwork_id,'') AS artwork_id,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id, deleted_at,
    enriched_at, created_at, updated_at
FROM tracks
WHERE tracks.deleted_at IS NULL
  AND LOWER(title)        = LOWER(?1)
  AND LOWER(album_artist) = LOWER(?2)
  AND LOWER(album_name)   = LOWER(?3)
  AND ABS(duration_ms - ?4) <= 2000
  AND path != ?5
LIMIT 1
`

type TrackDuplicateByMetaParams struct {
	Title       string
	AlbumArtist string
	AlbumName   string
	DurationMs  sql.NullInt64
	ExcludePath string
}

type TrackDuplicateByMetaRow struct {
	ID                  string
	Path                string
	Title               string
	ArtistID            string
	AlbumID             string
	ArtistName          string
	AlbumArtist         sql.NullString
	AlbumName           sql.NullString
	Genre               sql.NullString
	Year                sql.NullInt64
	TrackNumber         sql.NullInt64
	DiscNumber          sql.NullInt64
	DurationMs          sql.NullInt64
	BitrateKbps         sql.NullInt64
	SampleRateHz        sql.NullInt64
	Codec               sql.NullString
	FileSizeBytes       sql.NullInt64
	LastModified        string
	Fingerprint         sql.NullString
	AcousticFingerprint string
	MbRecordingID       sql.NullString
	ReplayGainTrack     sql.NullFloat64
	ReplayGainAlbum     sql.NullFloat64
	ArtworkID           string
	UploadedByUserID    string
	DeletedAt           sql.NullString
	EnrichedAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) TrackDuplicateByMeta(ctx context.Context, arg TrackDuplicateByMetaParams) (TrackDuplicateByMetaRow, error) {
	row := q.db.QueryRowContext(ctx, trackDuplicateByMeta,
		arg.Title,
		arg.AlbumArtist,
		arg.AlbumName,
		arg.DurationMs,
		arg.ExcludePath,
	)
	var i TrackDuplicateByMetaRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Title,
		&i.ArtistID,
		&i.AlbumID,
		&i.ArtistName,
		&i.AlbumArtist,
		&i.AlbumName,
		&i.Genre,
		&i.Year,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.SampleRateHz,
		&i.Codec,
		&i.FileSizeBytes,
		&i.LastModified,
		&i.Fingerprint,
		&i.AcousticFingerprint,
		&i.MbRecordingID,
		&i.ReplayGainTrack,
		&i.ReplayGainAlbum,
		&i.ArtworkID,
		&i.UploadedByUserID,
		&i.DeletedAt,
		&i.EnrichedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTrack = `-- name: UpsertTrack :exec
INSERT INTO tracks (
    id, path, title, artist_id, album_id, album_artist, album_name, genre, year,
    track_number, disc_number, duration_ms, bitrate_kbps, sample_rate_hz,
    codec, file_size_bytes, last_modified, fingerprint, acoustic_fingerprint, mb_recording_id,
    replay_gain_track, replay_gain_album, artwork_id, uploaded_by_user_id,
    enriched_at, created_at, updated_at
) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
ON CONFLICT(path) DO UPDATE SET
    title=excluded.title,
    artist_id=excluded.artist_id, album_id=excluded.album_id,
    album_artist=excluded.album_artist, album_name=excluded.album_name,
    genre=excluded.genre,
    year=excluded.year, track_number=excluded.track_number,
    disc_number=excluded.disc_number, duration_ms=excluded.duration_ms,
    bitrate_kbps=excluded.bitrate_kbps, sample_rate_hz=excluded.sample_rate_hz,
    codec=excluded.codec, file_size_bytes=excluded.file_size_bytes,
    last_modified=excluded.last_modified, fingerprint=excluded.fingerprint,
    acoustic_fingerprint=excluded.acoustic_fingerprint,
    mb_recording_id=excluded.mb_recording_id,
    replay_gain_track=excluded.replay_gain_track,
    replay_gain_album=excluded.replay_gain_album,
    artwork_id=excluded.artwork_id,
    uploaded_by_user_id=excluded.uploaded_by_user_id,
    enriched_at=excluded.enriched_at,
    updated_at=excluded.updated_at
`

type UpsertTrackParams struct {
	ID                  string
	Path                string
	Title               string
	ArtistID            sql.NullString
	AlbumID             sql.NullString
	AlbumArtist         sql.NullString
	AlbumName           sql.NullString
	Genre               sql.NullString
	Year                sql.NullInt64
	TrackNumber         sql.NullInt64
	DiscNumber          sql.NullInt64
	DurationMs          sql.NullInt64
	BitrateKbps         sql.NullInt64
	SampleRateHz        sql.NullInt64
	Codec               sql.NullString
	FileSizeBytes       sql.NullInt64
	LastModified        string
	Fingerprint         sql.NullString
	AcousticFingerprint string
	MbRecordingID       sql.NullString
	ReplayGainTrack     sql.NullFloat64
	ReplayGainAlbum     sql.NullFloat64
	ArtworkID           sql.NullString
	UploadedByUserID    sql.NullString
	EnrichedAt          sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrack,
		arg.ID,
		arg.Path,
		arg.Title,
		arg.ArtistID,
		arg.AlbumID,
		arg.AlbumArtist,
		arg.AlbumName,
		arg.Genre,
		arg.Year,
		arg.TrackNumber,
		arg.DiscNumber,
		arg.DurationMs,
		arg.BitrateKbps,
		arg.SampleRateHz,
		arg.Codec,
		arg.FileSizeBytes,
		arg.LastModified,
		arg.Fingerprint,
		arg.AcousticFingerprint,
		arg.MbRecordingID,
		arg.ReplayGainTrack,
		arg.ReplayGainAlbum,
		arg.ArtworkID,
		arg.UploadedByUserID,
		arg.EnrichedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
