// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracks.sql

package serverdb

import (
	"context"
	"database/sql"
	"strings"
)

const countTracks = `-- name: CountTracks :one
SELECT COUNT(*) FROM tracks WHERE tracks.deleted_at IS NULL
`

func (q *Queries) CountTracks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTracks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDuplicateFingerprints = `-- name: DeleteDuplicateFingerprints :execresult
DELETE FROM tracks
WHERE fingerprint != '' AND fingerprint IS NOT NULL
AND rowid NOT IN (
    SELECT MIN(rowid) FROM tracks
    WHERE fingerprint != '' AND fingerprint IS NOT NULL
    GROUP BY fingerprint
)
`

func (q *Queries) DeleteDuplicateFingerprints(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteDuplicateFingerprints)
}

const deleteTrackByPath = `-- name: DeleteTrackByPath :exec
DELETE FROM tracks WHERE tracks.path = ?
`

func (q *Queries) DeleteTrackByPath(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteTrackByPath, path)
	return err
}

const listTracks = `-- name: ListTracks :many
SELECT id, path, title,
    COALESCE(album_artist,'') AS album_artist, COALESCE(album_name,'') AS album_name,
    COALESCE(genre,'') AS genre, COALESCE(year,0) AS year,
    COALESCE(track_number,0) AS track_number, COALESCE(disc_number,0) AS disc_number,
    COALESCE(duration_ms,0) AS duration_ms, COALESCE(bitrate_kbps,0) AS bitrate_kbps,
    COALESCE(sample_rate_hz,0) AS sample_rate_hz, COALESCE(codec,'') AS codec,
    COALESCE(file_size_bytes,0) AS file_size_bytes, last_modified,
    COALESCE(fingerprint,'') AS fingerprint,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id,
    deleted_at, created_at, updated_at
FROM tracks WHERE tracks.deleted_at IS NULL ORDER BY title COLLATE NOCASE
`

type ListTracksRow struct {
	ID               string
	Path             string
	Title            string
	AlbumArtist      string
	AlbumName        string
	Genre            string
	Year             int64
	TrackNumber      int64
	DiscNumber       int64
	DurationMs       int64
	BitrateKbps      int64
	SampleRateHz     int64
	Codec            string
	FileSizeBytes    int64
	LastModified     string
	Fingerprint      string
	UploadedByUserID string
	DeletedAt        sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) ListTracks(ctx context.Context) ([]ListTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksRow
	for rows.Next() {
		var i ListTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.AlbumArtist,
			&i.AlbumName,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.SampleRateHz,
			&i.Codec,
			&i.FileSizeBytes,
			&i.LastModified,
			&i.Fingerprint,
			&i.UploadedByUserID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByAlbumName = `-- name: ListTracksByAlbumName :many
SELECT id, path, title,
    COALESCE(album_artist,'') AS album_artist, COALESCE(album_name,'') AS album_name,
    COALESCE(genre,'') AS genre, COALESCE(year,0) AS year,
    COALESCE(track_number,0) AS track_number, COALESCE(disc_number,0) AS disc_number,
    COALESCE(duration_ms,0) AS duration_ms, COALESCE(bitrate_kbps,0) AS bitrate_kbps,
    COALESCE(sample_rate_hz,0) AS sample_rate_hz, COALESCE(codec,'') AS codec,
    COALESCE(file_size_bytes,0) AS file_size_bytes, last_modified,
    COALESCE(fingerprint,'') AS fingerprint,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id,
    deleted_at, created_at, updated_at
FROM tracks WHERE tracks.deleted_at IS NULL AND album_name = ?
ORDER BY disc_number, track_number, title COLLATE NOCASE
`

type ListTracksByAlbumNameRow struct {
	ID               string
	Path             string
	Title            string
	AlbumArtist      string
	AlbumName        string
	Genre            string
	Year             int64
	TrackNumber      int64
	DiscNumber       int64
	DurationMs       int64
	BitrateKbps      int64
	SampleRateHz     int64
	Codec            string
	FileSizeBytes    int64
	LastModified     string
	Fingerprint      string
	UploadedByUserID string
	DeletedAt        sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) ListTracksByAlbumName(ctx context.Context, albumName sql.NullString) ([]ListTracksByAlbumNameRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracksByAlbumName, albumName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksByAlbumNameRow
	for rows.Next() {
		var i ListTracksByAlbumNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.AlbumArtist,
			&i.AlbumName,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.SampleRateHz,
			&i.Codec,
			&i.FileSizeBytes,
			&i.LastModified,
			&i.Fingerprint,
			&i.UploadedByUserID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByAlbumNameAndArtist = `-- name: ListTracksByAlbumNameAndArtist :many
SELECT id, path, title,
    COALESCE(album_artist,'') AS album_artist, COALESCE(album_name,'') AS album_name,
    COALESCE(genre,'') AS genre, COALESCE(year,0) AS year,
    COALESCE(track_number,0) AS track_number, COALESCE(disc_number,0) AS disc_number,
    COALESCE(duration_ms,0) AS duration_ms, COALESCE(bitrate_kbps,0) AS bitrate_kbps,
    COALESCE(sample_rate_hz,0) AS sample_rate_hz, COALESCE(codec,'') AS codec,
    COALESCE(file_size_bytes,0) AS file_size_bytes, last_modified,
    COALESCE(fingerprint,'') AS fingerprint,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id,
    deleted_at, created_at, updated_at
FROM tracks WHERE tracks.deleted_at IS NULL AND album_name = ? AND COALESCE(album_artist,'') = ?
ORDER BY disc_number, track_number, title COLLATE NOCASE
`

type ListTracksByAlbumNameAndArtistParams struct {
	AlbumName   sql.NullString
	AlbumArtist sql.NullString
}

type ListTracksByAlbumNameAndArtistRow struct {
	ID               string
	Path             string
	Title            string
	AlbumArtist      string
	AlbumName        string
	Genre            string
	Year             int64
	TrackNumber      int64
	DiscNumber       int64
	DurationMs       int64
	BitrateKbps      int64
	SampleRateHz     int64
	Codec            string
	FileSizeBytes    int64
	LastModified     string
	Fingerprint      string
	UploadedByUserID string
	DeletedAt        sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) ListTracksByAlbumNameAndArtist(ctx context.Context, arg ListTracksByAlbumNameAndArtistParams) ([]ListTracksByAlbumNameAndArtistRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracksByAlbumNameAndArtist, arg.AlbumName, arg.AlbumArtist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksByAlbumNameAndArtistRow
	for rows.Next() {
		var i ListTracksByAlbumNameAndArtistRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.AlbumArtist,
			&i.AlbumName,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.SampleRateHz,
			&i.Codec,
			&i.FileSizeBytes,
			&i.LastModified,
			&i.Fingerprint,
			&i.UploadedByUserID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByAlbumUnorganized = `-- name: ListTracksByAlbumUnorganized :many
SELECT id, path, title,
    COALESCE(album_artist,'') AS album_artist, COALESCE(album_name,'') AS album_name,
    COALESCE(genre,'') AS genre, COALESCE(year,0) AS year,
    COALESCE(track_number,0) AS track_number, COALESCE(disc_number,0) AS disc_number,
    COALESCE(duration_ms,0) AS duration_ms, COALESCE(bitrate_kbps,0) AS bitrate_kbps,
    COALESCE(sample_rate_hz,0) AS sample_rate_hz, COALESCE(codec,'') AS codec,
    COALESCE(file_size_bytes,0) AS file_size_bytes, last_modified,
    COALESCE(fingerprint,'') AS fingerprint,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id,
    deleted_at, created_at, updated_at
FROM tracks WHERE tracks.deleted_at IS NULL AND TRIM(COALESCE(album_name,''))=''
ORDER BY disc_number, track_number, title COLLATE NOCASE
`

type ListTracksByAlbumUnorganizedRow struct {
	ID               string
	Path             string
	Title            string
	AlbumArtist      string
	AlbumName        string
	Genre            string
	Year             int64
	TrackNumber      int64
	DiscNumber       int64
	DurationMs       int64
	BitrateKbps      int64
	SampleRateHz     int64
	Codec            string
	FileSizeBytes    int64
	LastModified     string
	Fingerprint      string
	UploadedByUserID string
	DeletedAt        sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) ListTracksByAlbumUnorganized(ctx context.Context) ([]ListTracksByAlbumUnorganizedRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracksByAlbumUnorganized)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksByAlbumUnorganizedRow
	for rows.Next() {
		var i ListTracksByAlbumUnorganizedRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.AlbumArtist,
			&i.AlbumName,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.SampleRateHz,
			&i.Codec,
			&i.FileSizeBytes,
			&i.LastModified,
			&i.Fingerprint,
			&i.UploadedByUserID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByIDs = `-- name: ListTracksByIDs :many
SELECT id, path, title,
    COALESCE(album_artist,'') AS album_artist, COALESCE(album_name,'') AS album_name,
    COALESCE(genre,'') AS genre, COALESCE(year,0) AS year,
    COALESCE(track_number,0) AS track_number, COALESCE(disc_number,0) AS disc_number,
    COALESCE(duration_ms,0) AS duration_ms, COALESCE(bitrate_kbps,0) AS bitrate_kbps,
    COALESCE(sample_rate_hz,0) AS sample_rate_hz, COALESCE(codec,'') AS codec,
    COALESCE(file_size_bytes,0) AS file_size_bytes, last_modified,
    COALESCE(fingerprint,'') AS fingerprint,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id,
    deleted_at, created_at, updated_at
FROM tracks
WHERE tracks.id IN (/*SLICE:ids*/?)
`

type ListTracksByIDsRow struct {
	ID               string
	Path             string
	Title            string
	AlbumArtist      string
	AlbumName        string
	Genre            string
	Year             int64
	TrackNumber      int64
	DiscNumber       int64
	DurationMs       int64
	BitrateKbps      int64
	SampleRateHz     int64
	Codec            string
	FileSizeBytes    int64
	LastModified     string
	Fingerprint      string
	UploadedByUserID string
	DeletedAt        sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) ListTracksByIDs(ctx context.Context, ids []string) ([]ListTracksByIDsRow, error) {
	query := listTracksByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksByIDsRow
	for rows.Next() {
		var i ListTracksByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.AlbumArtist,
			&i.AlbumName,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.SampleRateHz,
			&i.Codec,
			&i.FileSizeBytes,
			&i.LastModified,
			&i.Fingerprint,
			&i.UploadedByUserID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksPage = `-- name: ListTracksPage :many
SELECT id, path, title,
    COALESCE(album_artist,'') AS album_artist, COALESCE(album_name,'') AS album_name,
    COALESCE(genre,'') AS genre, COALESCE(year,0) AS year,
    COALESCE(track_number,0) AS track_number, COALESCE(disc_number,0) AS disc_number,
    COALESCE(duration_ms,0) AS duration_ms, COALESCE(bitrate_kbps,0) AS bitrate_kbps,
    COALESCE(sample_rate_hz,0) AS sample_rate_hz, COALESCE(codec,'') AS codec,
    COALESCE(file_size_bytes,0) AS file_size_bytes, last_modified,
    COALESCE(fingerprint,'') AS fingerprint,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id,
    deleted_at, created_at, updated_at
FROM tracks WHERE tracks.deleted_at IS NULL ORDER BY title COLLATE NOCASE LIMIT ? OFFSET ?
`

type ListTracksPageParams struct {
	Limit  int64
	Offset int64
}

type ListTracksPageRow struct {
	ID               string
	Path             string
	Title            string
	AlbumArtist      string
	AlbumName        string
	Genre            string
	Year             int64
	TrackNumber      int64
	DiscNumber       int64
	DurationMs       int64
	BitrateKbps      int64
	SampleRateHz     int64
	Codec            string
	FileSizeBytes    int64
	LastModified     string
	Fingerprint      string
	UploadedByUserID string
	DeletedAt        sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) ListTracksPage(ctx context.Context, arg ListTracksPageParams) ([]ListTracksPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracksPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksPageRow
	for rows.Next() {
		var i ListTracksPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.AlbumArtist,
			&i.AlbumName,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.SampleRateHz,
			&i.Codec,
			&i.FileSizeBytes,
			&i.LastModified,
			&i.Fingerprint,
			&i.UploadedByUserID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceTrackFile = `-- name: ReplaceTrackFile :exec
UPDATE tracks
SET path = ?, fingerprint = ?, file_size_bytes = ?, last_modified = ?, updated_at = ?
WHERE id = ?
`

type ReplaceTrackFileParams struct {
	Path          string
	Fingerprint   sql.NullString
	FileSizeBytes sql.NullInt64
	LastModified  string
	UpdatedAt     string
	ID            string
}

func (q *Queries) ReplaceTrackFile(ctx context.Context, arg ReplaceTrackFileParams) error {
	_, err := q.db.ExecContext(ctx, replaceTrackFile,
		arg.Path,
		arg.Fingerprint,
		arg.FileSizeBytes,
		arg.LastModified,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const restoreTrack = `-- name: RestoreTrack :exec
UPDATE tracks SET deleted_at = NULL, updated_at = ? WHERE id = ?
`

type RestoreTrackParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) RestoreTrack(ctx context.Context, arg RestoreTrackParams) error {
	_, err := q.db.ExecContext(ctx, restoreTrack, arg.UpdatedAt, arg.ID)
	return err
}

const searchTracksByIDs = `-- name: SearchTracksByIDs :many
SELECT id, path, title,
    COALESCE(album_artist,'') AS album_artist, COALESCE(album_name,'') AS album_name,
    COALESCE(genre,'') AS genre, COALESCE(year,0) AS year,
    COALESCE(track_number,0) AS track_number, COALESCE(disc_number,0) AS disc_number,
    COALESCE(duration_ms,0) AS duration_ms, COALESCE(bitrate_kbps,0) AS bitrate_kbps,
    COALESCE(sample_rate_hz,0) AS sample_rate_hz, COALESCE(codec,'') AS codec,
    COALESCE(file_size_bytes,0) AS file_size_bytes, last_modified,
    COALESCE(fingerprint,'') AS fingerprint,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id,
    deleted_at, created_at, updated_at
FROM tracks
WHERE tracks.deleted_at IS NULL
  AND tracks.id IN (/*SLICE:ids*/?)
`

type SearchTracksByIDsRow struct {
	ID               string
	Path             string
	Title            string
	AlbumArtist      string
	AlbumName        string
	Genre            string
	Year             int64
	TrackNumber      int64
	DiscNumber       int64
	DurationMs       int64
	BitrateKbps      int64
	SampleRateHz     int64
	Codec            string
	FileSizeBytes    int64
	LastModified     string
	Fingerprint      string
	UploadedByUserID string
	DeletedAt        sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) SearchTracksByIDs(ctx context.Context, ids []string) ([]SearchTracksByIDsRow, error) {
	query := searchTracksByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTracksByIDsRow
	for rows.Next() {
		var i SearchTracksByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.AlbumArtist,
			&i.AlbumName,
			&i.Genre,
			&i.Year,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.SampleRateHz,
			&i.Codec,
			&i.FileSizeBytes,
			&i.LastModified,
			&i.Fingerprint,
			&i.UploadedByUserID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTrack = `-- name: SoftDeleteTrack :exec
UPDATE tracks SET deleted_at = ?, updated_at = ? WHERE id = ?
`

type SoftDeleteTrackParams struct {
	DeletedAt sql.NullString
	UpdatedAt string
	ID        string
}

func (q *Queries) SoftDeleteTrack(ctx context.Context, arg SoftDeleteTrackParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteTrack, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const sumTrackBytes = `-- name: SumTrackBytes :one
SELECT CAST(COALESCE(SUM(file_size_bytes), 0) AS INTEGER) FROM tracks WHERE deleted_at IS NULL
`

func (q *Queries) SumTrackBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumTrackBytes)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const trackByFingerprint = `-- name: TrackByFingerprint :one
SELECT id, path, title,
    COALESCE(album_artist,'') AS album_artist, COALESCE(album_name,'') AS album_name,
    COALESCE(genre,'') AS genre, COALESCE(year,0) AS year,
    COALESCE(track_number,0) AS track_number, COALESCE(disc_number,0) AS disc_number,
    COALESCE(duration_ms,0) AS duration_ms, COALESCE(bitrate_kbps,0) AS bitrate_kbps,
    COALESCE(sample_rate_hz,0) AS sample_rate_hz, COALESCE(codec,'') AS codec,
    COALESCE(file_size_bytes,0) AS file_size_bytes, last_modified,
    COALESCE(fingerprint,'') AS fingerprint,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id,
    deleted_at, created_at, updated_at
FROM tracks WHERE tracks.fingerprint = ? AND fingerprint != '' LIMIT 1
`

type TrackByFingerprintRow struct {
	ID               string
	Path             string
	Title            string
	AlbumArtist      string
	AlbumName        string
	Genre            string
	Year             int64
	TrackNumber      int64
	DiscNumber       int64
	DurationMs       int64
	BitrateKbps      int64
	SampleRateHz     int64
	Codec            string
	FileSizeBytes    int64
	LastModified     string
	Fingerprint      string
	UploadedByUserID string
	DeletedAt        sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) TrackByFingerprint(ctx context.Context, fingerprint sql.NullString) (TrackByFingerprintRow, error) {
	row := q.db.QueryRowContext(ctx, trackByFingerprint, fingerprint)
	var i TrackByFingerprintRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Title,
		&i.AlbumArtist,
		&i.AlbumName,
		&i.Genre,
		&i.Year,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.SampleRateHz,
		&i.Codec,
		&i.FileSizeBytes,
		&i.LastModified,
		&i.Fingerprint,
		&i.UploadedByUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trackByID = `-- name: TrackByID :one
SELECT id, path, title,
    COALESCE(album_artist,'') AS album_artist, COALESCE(album_name,'') AS album_name,
    COALESCE(genre,'') AS genre, COALESCE(year,0) AS year,
    COALESCE(track_number,0) AS track_number, COALESCE(disc_number,0) AS disc_number,
    COALESCE(duration_ms,0) AS duration_ms, COALESCE(bitrate_kbps,0) AS bitrate_kbps,
    COALESCE(sample_rate_hz,0) AS sample_rate_hz, COALESCE(codec,'') AS codec,
    COALESCE(file_size_bytes,0) AS file_size_bytes, last_modified,
    COALESCE(fingerprint,'') AS fingerprint,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id,
    deleted_at, created_at, updated_at
FROM tracks WHERE tracks.id = ? LIMIT 1
`

type TrackByIDRow struct {
	ID               string
	Path             string
	Title            string
	AlbumArtist      string
	AlbumName        string
	Genre            string
	Year             int64
	TrackNumber      int64
	DiscNumber       int64
	DurationMs       int64
	BitrateKbps      int64
	SampleRateHz     int64
	Codec            string
	FileSizeBytes    int64
	LastModified     string
	Fingerprint      string
	UploadedByUserID string
	DeletedAt        sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) TrackByID(ctx context.Context, id string) (TrackByIDRow, error) {
	row := q.db.QueryRowContext(ctx, trackByID, id)
	var i TrackByIDRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Title,
		&i.AlbumArtist,
		&i.AlbumName,
		&i.Genre,
		&i.Year,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.SampleRateHz,
		&i.Codec,
		&i.FileSizeBytes,
		&i.LastModified,
		&i.Fingerprint,
		&i.UploadedByUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trackByPath = `-- name: TrackByPath :one
SELECT id, path, title,
    COALESCE(album_artist,'') AS album_artist, COALESCE(album_name,'') AS album_name,
    COALESCE(genre,'') AS genre, COALESCE(year,0) AS year,
    COALESCE(track_number,0) AS track_number, COALESCE(disc_number,0) AS disc_number,
    COALESCE(duration_ms,0) AS duration_ms, COALESCE(bitrate_kbps,0) AS bitrate_kbps,
    COALESCE(sample_rate_hz,0) AS sample_rate_hz, COALESCE(codec,'') AS codec,
    COALESCE(file_size_bytes,0) AS file_size_bytes, last_modified,
    COALESCE(fingerprint,'') AS fingerprint,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id,
    deleted_at, created_at, updated_at
FROM tracks WHERE tracks.path = ? LIMIT 1
`

type TrackByPathRow struct {
	ID               string
	Path             string
	Title            string
	AlbumArtist      string
	AlbumName        string
	Genre            string
	Year             int64
	TrackNumber      int64
	DiscNumber       int64
	DurationMs       int64
	BitrateKbps      int64
	SampleRateHz     int64
	Codec            string
	FileSizeBytes    int64
	LastModified     string
	Fingerprint      string
	UploadedByUserID string
	DeletedAt        sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) TrackByPath(ctx context.Context, path string) (TrackByPathRow, error) {
	row := q.db.QueryRowContext(ctx, trackByPath, path)
	var i TrackByPathRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Title,
		&i.AlbumArtist,
		&i.AlbumName,
		&i.Genre,
		&i.Year,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.SampleRateHz,
		&i.Codec,
		&i.FileSizeBytes,
		&i.LastModified,
		&i.Fingerprint,
		&i.UploadedByUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trackDuplicateByMeta = `-- name: TrackDuplicateByMeta :one
SELECT id, path, title,
    COALESCE(album_artist,'') AS album_artist, COALESCE(album_name,'') AS album_name,
    COALESCE(genre,'') AS genre, COALESCE(year,0) AS year,
    COALESCE(track_number,0) AS track_number, COALESCE(disc_number,0) AS disc_number,
    COALESCE(duration_ms,0) AS duration_ms, COALESCE(bitrate_kbps,0) AS bitrate_kbps,
    COALESCE(sample_rate_hz,0) AS sample_rate_hz, COALESCE(codec,'') AS codec,
    COALESCE(file_size_bytes,0) AS file_size_bytes, last_modified,
    COALESCE(fingerprint,'') AS fingerprint,
    COALESCE(uploaded_by_user_id,'') AS uploaded_by_user_id,
    deleted_at, created_at, updated_at
FROM tracks
WHERE tracks.deleted_at IS NULL
  AND LOWER(title)        = LOWER(?1)
  AND LOWER(album_artist) = LOWER(?2)
  AND LOWER(album_name)   = LOWER(?3)
  AND ABS(duration_ms - ?4) <= 2000
  AND path != ?5
LIMIT 1
`

type TrackDuplicateByMetaParams struct {
	Title       string
	AlbumArtist string
	AlbumName   string
	DurationMs  sql.NullInt64
	ExcludePath string
}

type TrackDuplicateByMetaRow struct {
	ID               string
	Path             string
	Title            string
	AlbumArtist      string
	AlbumName        string
	Genre            string
	Year             int64
	TrackNumber      int64
	DiscNumber       int64
	DurationMs       int64
	BitrateKbps      int64
	SampleRateHz     int64
	Codec            string
	FileSizeBytes    int64
	LastModified     string
	Fingerprint      string
	UploadedByUserID string
	DeletedAt        sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) TrackDuplicateByMeta(ctx context.Context, arg TrackDuplicateByMetaParams) (TrackDuplicateByMetaRow, error) {
	row := q.db.QueryRowContext(ctx, trackDuplicateByMeta,
		arg.Title,
		arg.AlbumArtist,
		arg.AlbumName,
		arg.DurationMs,
		arg.ExcludePath,
	)
	var i TrackDuplicateByMetaRow
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Title,
		&i.AlbumArtist,
		&i.AlbumName,
		&i.Genre,
		&i.Year,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.SampleRateHz,
		&i.Codec,
		&i.FileSizeBytes,
		&i.LastModified,
		&i.Fingerprint,
		&i.UploadedByUserID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTrack = `-- name: UpsertTrack :exec
INSERT INTO tracks (
    id, path, title, album_artist, album_name, genre, year,
    track_number, disc_number, duration_ms, bitrate_kbps, sample_rate_hz,
    codec, file_size_bytes, last_modified, fingerprint,
    uploaded_by_user_id,
    created_at, updated_at
) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
ON CONFLICT(path) DO UPDATE SET
    title=excluded.title,
    album_artist=excluded.album_artist, album_name=excluded.album_name,
    genre=excluded.genre,
    year=excluded.year, track_number=excluded.track_number,
    disc_number=excluded.disc_number, duration_ms=excluded.duration_ms,
    bitrate_kbps=excluded.bitrate_kbps, sample_rate_hz=excluded.sample_rate_hz,
    codec=excluded.codec, file_size_bytes=excluded.file_size_bytes,
    last_modified=excluded.last_modified, fingerprint=excluded.fingerprint,
    uploaded_by_user_id=excluded.uploaded_by_user_id,
    updated_at=excluded.updated_at
`

type UpsertTrackParams struct {
	ID               string
	Path             string
	Title            string
	AlbumArtist      sql.NullString
	AlbumName        sql.NullString
	Genre            sql.NullString
	Year             sql.NullInt64
	TrackNumber      sql.NullInt64
	DiscNumber       sql.NullInt64
	DurationMs       sql.NullInt64
	BitrateKbps      sql.NullInt64
	SampleRateHz     sql.NullInt64
	Codec            sql.NullString
	FileSizeBytes    sql.NullInt64
	LastModified     string
	Fingerprint      sql.NullString
	UploadedByUserID sql.NullString
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrack,
		arg.ID,
		arg.Path,
		arg.Title,
		arg.AlbumArtist,
		arg.AlbumName,
		arg.Genre,
		arg.Year,
		arg.TrackNumber,
		arg.DiscNumber,
		arg.DurationMs,
		arg.BitrateKbps,
		arg.SampleRateHz,
		arg.Codec,
		arg.FileSizeBytes,
		arg.LastModified,
		arg.Fingerprint,
		arg.UploadedByUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
