// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package serverdb

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id,
    username,
    password_hash,
    is_admin,
    can_upload,
    can_edit,
    can_delete,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string
	Username     string
	PasswordHash string
	IsAdmin      bool
	CanUpload    bool
	CanEdit      bool
	CanDelete    bool
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.IsAdmin,
		arg.CanUpload,
		arg.CanEdit,
		arg.CanDelete,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    username,
    password_hash,
    is_admin,
    can_upload,
    can_edit,
    can_delete,
    created_at,
    updated_at
FROM users
ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.CanUpload,
			&i.CanEdit,
			&i.CanDelete,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ?, updated_at = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	UpdatedAt    string
	ID           string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserPermissions = `-- name: UpdateUserPermissions :exec
UPDATE users SET can_upload = ?, can_edit = ?, can_delete = ?, updated_at = ?
WHERE id = ?
`

type UpdateUserPermissionsParams struct {
	CanUpload bool
	CanEdit   bool
	CanDelete bool
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateUserPermissions(ctx context.Context, arg UpdateUserPermissionsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPermissions,
		arg.CanUpload,
		arg.CanEdit,
		arg.CanDelete,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const userByID = `-- name: UserByID :one
SELECT
    id,
    username,
    password_hash,
    is_admin,
    can_upload,
    can_edit,
    can_delete,
    created_at,
    updated_at
FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) UserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CanUpload,
		&i.CanEdit,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userByUsername = `-- name: UserByUsername :one
SELECT
    id,
    username,
    password_hash,
    is_admin,
    can_upload,
    can_edit,
    can_delete,
    created_at,
    updated_at
FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) UserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CanUpload,
		&i.CanEdit,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
