// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseLocalFolder() {
  return window['go']['main']['App']['ChooseLocalFolder']();
}

export function ConnectToServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectToServer'](arg1, arg2, arg3);
}

export function DisconnectFromServer() {
  return window['go']['main']['App']['DisconnectFromServer']();
}

export function GetLocalPort() {
  return window['go']['main']['App']['GetLocalPort']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetToken() {
  return window['go']['main']['App']['GetToken']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function OpenLocalFiles() {
  return window['go']['main']['App']['OpenLocalFiles']();
}

export function OpenLocalFolder() {
  return window['go']['main']['App']['OpenLocalFolder']();
}

export function ScanLocalFolder(arg1) {
  return window['go']['main']['App']['ScanLocalFolder'](arg1);
}

export function UploadLocalFile(arg1) {
  return window['go']['main']['App']['UploadLocalFile'](arg1);
}
