// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppDBDelete(arg1) {
  return window['go']['main']['App']['AppDBDelete'](arg1);
}

export function AppDBGet(arg1) {
  return window['go']['main']['App']['AppDBGet'](arg1);
}

export function AppDBSet(arg1, arg2) {
  return window['go']['main']['App']['AppDBSet'](arg1, arg2);
}

export function ChooseLocalFolder() {
  return window['go']['main']['App']['ChooseLocalFolder']();
}

export function ClearArtworkCache() {
  return window['go']['main']['App']['ClearArtworkCache']();
}

export function ClearLocalFolder(arg1) {
  return window['go']['main']['App']['ClearLocalFolder'](arg1);
}

export function ConnectToServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectToServer'](arg1, arg2, arg3);
}

export function DisconnectFromServer() {
  return window['go']['main']['App']['DisconnectFromServer']();
}

export function FindLocalDuplicates(arg1) {
  return window['go']['main']['App']['FindLocalDuplicates'](arg1);
}

export function GetLocalAlbumGroups(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetLocalAlbumGroups'](arg1, arg2, arg3, arg4);
}

export function GetLocalAlbumTracks(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLocalAlbumTracks'](arg1, arg2, arg3);
}

export function GetLocalPort() {
  return window['go']['main']['App']['GetLocalPort']();
}

export function GetLocalTracks(arg1) {
  return window['go']['main']['App']['GetLocalTracks'](arg1);
}

export function GetLocalTracksByPaths(arg1) {
  return window['go']['main']['App']['GetLocalTracksByPaths'](arg1);
}

export function GetLocalTracksPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLocalTracksPage'](arg1, arg2, arg3);
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetToken() {
  return window['go']['main']['App']['GetToken']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function OpenLocalFiles() {
  return window['go']['main']['App']['OpenLocalFiles']();
}

export function OpenLocalFolder() {
  return window['go']['main']['App']['OpenLocalFolder']();
}

export function RestoreSession(arg1, arg2) {
  return window['go']['main']['App']['RestoreSession'](arg1, arg2);
}

export function ScanLocalFolderStream(arg1) {
  return window['go']['main']['App']['ScanLocalFolderStream'](arg1);
}

export function SearchLocalTracks(arg1, arg2) {
  return window['go']['main']['App']['SearchLocalTracks'](arg1, arg2);
}

export function UploadLocalFile(arg1) {
  return window['go']['main']['App']['UploadLocalFile'](arg1);
}
