// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerPort():Promise<number>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function TriggerScan():Promise<void>;
