// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseLocalFolder():Promise<string>;

export function ConnectToServer(arg1:string,arg2:string,arg3:string):Promise<main.ConnectResult>;

export function DisconnectFromServer():Promise<void>;

export function GetLocalPort():Promise<number>;

export function GetServerURL():Promise<string>;

export function GetToken():Promise<string>;

export function IsConnected():Promise<boolean>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenLocalFiles():Promise<Array<string>>;

export function OpenLocalFolder():Promise<Array<string>>;

export function ScanLocalFolder(arg1:string):Promise<Array<main.LocalTrack>>;

export function UploadLocalFile(arg1:string):Promise<string>;
