// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerPort() {
  return window['go']['main']['App']['GetServerPort']();
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function TriggerScan() {
  return window['go']['main']['App']['TriggerScan']();
}
