// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppDBDelete(arg1:string):Promise<void>;

export function AppDBGet(arg1:string):Promise<string>;

export function AppDBSet(arg1:string,arg2:string):Promise<void>;

export function ChooseLocalFolder():Promise<string>;

export function ClearLocalFolder(arg1:string):Promise<void>;

export function ConnectToServer(arg1:string,arg2:string,arg3:string):Promise<main.ConnectResult>;

export function DisconnectFromServer():Promise<void>;

export function FindLocalDuplicates(arg1:Array<string>):Promise<Array<main.LocalDuplicateGroup>>;

export function GetLocalPort():Promise<number>;

export function GetLocalTracks(arg1:Array<string>):Promise<Array<main.LocalTrack>>;

export function GetServerURL():Promise<string>;

export function GetToken():Promise<string>;

export function IsConnected():Promise<boolean>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenLocalFiles():Promise<Array<string>>;

export function OpenLocalFolder():Promise<Array<string>>;

export function RestoreSession(arg1:string,arg2:string):Promise<void>;

export function ScanLocalFolderStream(arg1:string):Promise<void>;

export function UploadLocalFile(arg1:string):Promise<string>;
