name: Wails build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      target_ref:
        description: 'Branch or tag to build (e.g. v1.2.3 or refs/tags/v1.2.3)'
        required: true
        default: 'v1.2.3'

env:
  APP_NAME: "pneuma"

jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - platform: "linux/amd64"
            os: "ubuntu-latest"
          - platform: "windows/amd64"
            os: "windows-latest"
          - platform: "darwin/universal"
            os: "macos-latest"

    # https://github.com/dAppServer/wails-build-action/tree/dev/actions/build/wails2#wails-v2-full-pipeline 
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppCore/build@v4 
        id: build
        with:
          build-name: ${{ env.APP_NAME }}
          build-platform: ${{ matrix.build.platform }}
          # go-version: "1.23"
          # need to keep node at 22.x rather than latest to avoid build issues with
          # libwebkit2gtk-4.0-dev (AFAIK, ubuntu 24 drops this specific package). This
          # version is needed to work with wails
          # node-version: "22.x"

      # - name: Build wails
      #   uses: dAppServer/wails-build-action@v2.2
      #   id: build
      #   with:
      #     build-name: ${{ env.APP_NAME }}
      #     build-platform: ${{ matrix.build.platform }}
      #     package: true
      #     go-version: "1.23"
      #     # need to keep node at 22.x rather than latest to avoid build issues with
      #     # libwebkit2gtk-4.0-dev (AFAIK, ubuntu 24 drops this specific package). This
      #     # version is needed to work with wails
      #     # See linux installation here: https://wails.io/docs/gettingstarted/installation/
      #     node-version: "22.x"
