name: Wails build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      target_ref:
        description: "Branch or tag to build (e.g. v1.2.3 or refs/tags/v1.2.3)"
        required: true
        default: "v1.2.3"

env:
  APP_NAME: "pneuma"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - platform: "linux/amd64"
            os: "ubuntu-latest"
          - platform: "windows/amd64"
            os: "windows-latest"
          - platform: "darwin/universal"
            os: "macos-latest"

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # https://github.com/dAppServer/wails-build-action/tree/dev/actions/build/wails2#wails-v2-full-pipeline
      - name: Build wails
        uses: dAppCore/build/actions/build/wails2@v4.0.0
        id: build
        with:
          build-name: ${{ env.APP_NAME }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: "1.23"
          # need to keep node at 22.x rather than latest to avoid build issues with
          # libwebkit2gtk-4.0-dev (AFAIK, ubuntu 24 drops this specific package) as well
          # as get Vite to work properly. This version is needed to work with wails
          node-version: "22.x"

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: pneuma-desktop-${{ matrix.build.os }}
          path: build/bin/*
          retention-days: 1

  release:
    name: Create GitHub Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all binary artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
          pattern: pneuma-desktop-*

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
          generate_release_notes: true
